package arheo.storytime;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;

import arheo.storytime.PhraseList.Phrase;

import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.item.ItemStack;
import static arheo.storytime.PhraseList.Phrase.*;
import static arheo.storytime.Phrases.*;

public enum Symbol {

	FOURTY_NUMBER(null){
		private Random rand = new Random();
		@Override
		public Phrase getPhrase() {
			return new Phrase(String.valueOf((int)Math.floor(39*rand.nextDouble()*rand.nextDouble())+1),1.0);		
		}
	},
	
	TWOHUNDRED_NUMBER(null){
		private Random rand = new Random();
		@Override
		public Phrase getPhrase() {
			return new Phrase(String.valueOf((int)Math.floor(200*rand.nextDouble()*rand.nextDouble())+1),1.0);		
		}
	},
	
	TESTPAGE(new PhraseList(
			"#SENT_A# #SENT_J#. #SENT_I#. #SENT_K#. More news #TIMES_FUTURE#.",
			""
			
			
	)),
	
	//REC_F NEEDS REWRITING
	
	TESTPAGE2(new PhraseList(
			"#REC_H#.\n#INGREDIENTS#\n#OVENPREP#. #REC_D#. #REC_E#. #REC_G#. #REC_I#.\n#REC_F#.",
			"#INGREDIENTS#\n #OVENPREP#. #REC_AB#. #REC_IB#. #REC_BB#. #REC_G#.\n#REC_F#.",
			
			""
	)),
	
	
	INGREDIENTS(new PhraseList(
			"#REC_A# #REC_C# the following: \n\n #FOURTY_NUMBER##IMP# #FOOD_BASIC+~PREP1# \n #FOURTY_NUMBER##IMP# #FOOD_BASIC+~PREP2# \n #FOURTY_NUMBER##IMP# #FOOD_BASIC+~PREP3#\n",
			""
			
	)),
	
	OVENPREP(new PhraseList(
			w("First, #OP1# your #COOKER+~COOK1# to #OVENTEMP+~TEMP1#", 0.75),
			"This recipe requires a #COOKER+~COOK1# and a #COOKER+~COOK2#",
			"Using a #COOKER+~COOK1# is highly recommended, however a #COOKER+~COOK2# will suffice",
			"We'll be using a #COOKER+~COOK1# for this, but don't worry! A #COOKER+~COOK2# will do the trick",
			"The optimal temperature for producing this #FOOD_PRODUCT+~PROD1# is #OVENTEMP+~TEMP1#",
			"Ideally, a #COOKER+~COOK1# set to #OVENTEMP+~TEMP1# should be at your disposal",
			"We'll need to bung the #FOOD_BASIC+~PREP3# in the #COOKER+~COOK1# for #FOURTY_NUMBER# minutes whilst handling the next step",
			"Before starting the next step, place 2 #IMP# of #FOOD_BASIC+~PREP1# in a #COOKER+~COOK1#, for use as a garnish",
			""
			
	)),
	
	REC_AB(new PhraseList(
			"We'll begin by making a light #FOOD_BASIC+~PREP1# #MUSH#. #FOOD_PREP_1# the #FOOD_BASIC+~PREP1# and the #FOOD_BASIC+~PREP2# together until they reach a #CONSISTENCY# consistency",
			"#OP1# the #FOOD_BASIC+~PREP1# to #FOURTY_NUMBER# #OVENTEMP#, and continue to #FOOD_PREP_1# the #FOOD_BASIC+~PREP2#",
			"You'll need to pop most of the the #FOOD_BASIC+~PREP2# into a #SIZE2# #POTS+~POT1#, and gently #FOOD_PREP_2#",
			"Throw the lot into a #SIZE2# #POTS+~POT1#. #FOOD_PREP_2+%CAP#",
			""
			
			
	)),
	
	REC_BB(new PhraseList(
			"Take a #ACTIVITYCONC#, then check the #COOKER+~COOK1#",
			"Now would be the ideal time for a #ACTIVITYCONC#. Once completed, #FOOD_PREP_4# the #FOOD_BASIC+~PREP3# and prepare to #FOOD_PREP_3# the #FOOD_PRODUCT+~PROD1#.",
			"#REC_D#",
			""
			
	)),
	
	ACTIVITYCONC(new PhraseList(
			"#LENGTHTIME# #ACTIVITY#",
			"#LENGTHTIME# #ACTIVITY#",
			"#LENGTHTIME# #ACTIVITY#",
			w("#ACTIVITY#", 2.0),
			""
			
			
			
	)),
	
	ACTIVITY(new PhraseList(
			"walk",
			"stroll",
			"bath",
			"time to appreciate the finer #NOUNS_BASIC_PLURAL# in life",
			"hang-gliding session",
			"painting class",
			"debt recovery seminar",
			"break",
			"moment",
			"moment to engage in #CRIME#",
			"meditation",
			""
			
	)),
	
	LENGTHTIME(new PhraseList(
			"short",
			"long",
			"very #LENGTH#",
			"quick",
			"brisk",
			"mildly extended",
			"vigorous",
			"relaxing",
			"moderate",
			"lengthy",
			""
			
			
			
	)),
	
	OP1(new PhraseList(
			"heat",
			"turn up",
			"warm up",
			"cool down",
			"assign",
			"dial up",
			"order",
			"command",
			"preheat",
			"crank up",
			""
	)),
	
	COOKER(new PhraseList(
			"oven",
			"microwave",
			"cooker",
			"hob",
			"grill",
			"fridge",
			"bread-maker",
			"slow-cooker",
			"pressure-cooker",
			"hyperbaric chamber",
			"cryogenic cooking pod",
			"stove",
			"hearth",
			"fire pit",
			"complicated array of lenses, powered by the sun",
			"lava furnace",
			"furnace",
			""
			
	)),
	
	OVENTEMP(new PhraseList(
			"#TWOHUNDRED_NUMBER# #TEMPUNITS#",
			"#TWOHUNDRED_NUMBER# #TEMPUNITS#",
			"#FOURTY_NUMBER# #TEMPUNITS#",
			"Gas Mark #FOURTY_NUMBER#",
			w("#TWOHUNDRED_NUMBER# #TEMPUNITS#", 0.5),
			""
			
	)),
	
	TEMPUNITS(new PhraseList(
			"Celsius",
			"Fahrenheit",
			w("Kelvin", 0.5),
			"Kilowatt Hours",
			"Accumulated Thermal Units",
			"Gradus Caloris",
			"Newtons",
			"Units of Redstone Flux",
			"Electrical Units",
			"Watts",
			w("x10^#FOURTY_NUMBER# eV", 0.25),
			""
	)),
	
	IMP(new PhraseList(
			"lb",
			"oz",
			"fl oz",
			w("t", 0.25),
			"dr",
			"gr",
			w("cwt", 0.25),
			"qtr",
			w("troy oz", 0.1),
			""
			
	)),
	
	REC_A(new PhraseList(
			w("This week", 0.5),
			"Today",
			"In today's session",
			"Continuing from last week's exercise",
			"Before getting started",
			"To prepare this dish",
			"Prior to cooking",
			"To start,",
			"As is customary, say a short prayer, then",
			"Begin by",
			""
	)),
			
	
	REC_C(new PhraseList(
			"you will need to acquire",
			"you must purchase",
			"hunt down",
			"farm",
			"gather",
			"acquire",
			"thoroughly wash",
			w("have your servant bring you", 0.5),
			"conjure up",
			w("pray to the gods for", 0.25),
			"assemble",
			"find",
			"retrieve",
			"collect",
			w("will into existence", 0.25),
			""
					
					
	)),
	
	REC_D(new PhraseList(
			"#ADV+%CAP# #FOOD_PREP_1# the #SEASONING+~PREP1#, and #FOOD_PREP_2# for #FOURTY_NUMBER# minutes",
			"#FOOD_PREP_1+%CAP# the #SEASONING+~PREP1#, then #FOOD_PREP_2#, #ADV#",
			"#FOOD_PREP_1+%CAP# the #FOOD_BASIC+~PREP1#, and #FOOD_PREP_2+~BAKE1#. As the #FOOD_BASIC+~PREP1# #FOOD_PREP_2+~BAKE1#s, #FOOD_PREP_1# the #FOOD_BASIC+~PREP2#",
			"#IMPLEMENT+~MIX1#, then #FOOD_PREP_1# the #SEASONING+~PREP1# with a little #SEASONING#",
			"Take a #POTS+~POT1#, and #FOOD_PREP_1# all the ingredients into a #MUSH#",
			"In a #POTS+~POT1#, create a #MUSH# using half of the #FOOD_BASIC+~PREP3#",
			"#FOOD_PREP_1+%CAP# the #FOOD_BASIC+~PREP2# in a #POTS+~POT1# until it becomes #CONSISTENCY+~CON1#",
			"#FOOD_PREP_4+%CAP# the #FOOD_BASIC+~PREP1# until it is #CONSISTENCY+~CON1# and place in a #POTS+~POT1#",
			"Place the #FOOD_BASIC+~PREP1# in a warm #POTS+~POT1#, then make a #CONSISTENCY# #MUSH+MUSH1# out of a handful of the #FOOD_BASIC+~PREP3#, and add it to the #POTS+~POT1#",
			""
			
	)),
	
	CONSISTENCY(new PhraseList(
			"light",
			"fluffy",
			"#CONSISTENCY# and #CONSISTENCY#",
			"dense",
			"coarse",
			"lumpy",
			"cracked",
			"shattered",
			"liquid",
			"pureed",
			"fine",
			"granulated",
			"crystalline",
			w("igneous", 0.25),
			w("irradiated", 0.25),
			"puffy",
			"stiff",
			"soft",
			"hard",
			"solid",
			"a mess on the floor",
			"runny",
			"gelatinous",
			"purified",
			""
			
	)),
	
	
	IMPLEMENT(new PhraseList(
			"Acquire a #POTS+~POT1#",
			"Take a #POTS+~POT1#",
			"Grab a #POTS+~POT1#",
			"Place half of the #FOOD_BASIC+~PREP1# and a handful of #FOOD_BASIC+~PREP3# into a #POTS+~POT1#",
			"Oil a #POTS+~POT1#",
			"Flour a #POTS+~POT1#",
			"Warm a #POTS+~POT1# in your #COOKER+~COOK1#",
			""
			
			
	)),
	
	MUSH(new PhraseList(
			"mixture",
			"paste",
			"lump",
			"batter",
			"dough",
			"coarse powder",
			"fine porridge",
			"lumpy mess",
			"solid mass",
			"cube",
			"dense filling",
			""
			
			
	)),
	
	POTS(new PhraseList(
			"mixing bowl",
			"jug",
			"pot",
			"pan",
			"wok",
			"ramekin",
			"wooden mixing platter",
			"kneading bowl",
			"clear surface",
			"disinfected table-top",
			"gold plated ornery coagulation urn",
			"tray",
			""
			
	)),
	
	CREATE(new PhraseList(
			""
			
	)),
	
	FOOD_PREP_1(new PhraseList(
			"chop",
			"fillet",
			"cut",
			"beat",
			"blanche",
			"flatten",
			"dice",
			"mince",
			"roll",
			"trim",
			"wash",
			w("lick", 0.25),
			"slice",
			"cleave",
			"clean",
			"prepare",
			"skin",
			"peel",
			"skewer",
			"stir",
			"cure",
			"wrap",
			"shake",
			""
			
			
	)),
	
	FOOD_PREP_2(new PhraseList(
			"boil",
			"broil",
			"simmer",
			"roast",
			"stew",
			"fry",
			"deep-fry",
			"toast",
			"scorch",
			"sear",
			"batter",
			w("lick", 0.25),
			"bake",
			"smoke",
			"microwave",
			"stir-fry",
			"poach",
			""
			
			
	)),
	
	FOOD_PREP_3(new PhraseList(
			"garnish",
			"decorate",
			"ice",
			"complete",
			"drizzle",
			"brush",
			"coat",
			"sprinkle",
			"glaze",
			"ornament",
			"stack",
			""
			
	)),
	
	SIZE2(new PhraseList(
			" big",
			w(" small", 2.0),
			w(" large", 2.0),
			w(" moderately sized", 2.0),
			" tiny",
			" huge",
			"n average",
			" colossal",
			" vast",
			" minute",
			"n infitesimally small",
			" gargantuan",
			"n unholy",
			" super #SIZE1#",
			"n extra #SIZE1#",
			""
	)),
	
	SIZE1(new PhraseList(
			"big",
			w("small", 2.0),
			w("large", 2.0),
			w("moderately sized", 2.0),
			"tiny",
			"huge",
			"average",
			"colossal",
			"vast",
			"minute",
			"infitesimally small",
			"gargantuan",
			"unholy",
			"super #SIZE1#",
			"extra #SIZE1#",
			""
	)),
	
	
	FOOD_PREP_4(new PhraseList(
			"forge",
			"fold",
			"form",
			"pack",
			"roll",
			"mix",
			"stir",
			"assemble",
			"stretch",
			"cast",
			"build",
			""
			
			
	)),
	
	FINALLY(new PhraseList(
			w("All that remains is to", 0.5),
			"When you are ready,",
			"After washing your hands,",
			"Once the ingredients have been cooked,",
			"Finally,",
			"Then, with great care",
			"Taking care to avoid mess,",
			""
			
			
			
	)),
	
	
	REC_I(new PhraseList(
			"#FINALLY# #FOOD_PREP_4# the product into the perfect collection of #SEASONING+~PROD1#",
			"#FOOD_PREP_4+%CAP# the mixture into #SIZE1# #SEASONING+~PROD1#",
			"#FINALLY# #FOOD_PREP_4# a mound of #SIZE1# #SEASONING+~PROD1#, and #FOOD_PREP_2# until ready",
			"If you followed this recipe correctly, you should have an aromatic #FOOD_BASIC+~PREP1# #MUSH+~MUSH1#. #FOOD_PREP_4+%CAP# this into #FOOD_PRODUCT+~PROD1#",
			""
			
			
	)),
	
	REC_IB(new PhraseList(
			"#REC_I#",
			"This should have given the mixture time to #FINISHING#. Apply the prepared #FOOD_BASIC+~PREP3#. #FINALLY# #FOOD_PREP_4# the #FOOD_PRODUCT+~PROD1#",
			""
			
	)),
	
	
	REC_E(new PhraseList(
			"#TIMES_FUTURE#, add a handful of #SEASONING+~PREP3#, then place in the #COOKER+~COOK1# for a further #FOURTY_NUMBER# minutes",
			"Add in some #SEASONING+~PREP2#, and a little #SEASONING+~PREP3#",
			"#TIMES_FUTURE#, add the remaining #SEASONING+~PREP2#, #FOOD_PREP_2# #ADV#, then liberally apply the #SEASONING+~PREP3#",
			"#TIMES_FUTURE#, combine the ingredients, and place the finished #MUSH+~MUSH1# gently in the #COOKER+~COOK1#",
			"Combine all the remaining ingredients into your #POTS+~POT1#, and #FOOD_PREP_4#",
			"Into your #POTS+~POT1#, #FOOD_PREP_4# the prepared #FOOD_BASIC+~PREP1# and the #FOOD_PRODUCT+~MUSH1#, before placing into the #COOKER+~COOK1# to #FOOD_PREP_2#",
			""
			
	)),
	
	REC_F(new PhraseList(
			w("Enjoy responsibly", 0.5),
			"Serve with #THINGS#",
			"Serves #FOURTY_NUMBER#",
			"This dish is popular with #PEOPLE_PLURAL#",
			""
	)),
	
	REC_G(new PhraseList(
			"Finally, use any remaining #FOOD_BASIC+~PREP1# to #FOOD_PREP_3# the dish",
			"#FOOD_PREP_3+%CAP# with #SEASONING+~PREP3#, and #SERVE#",
			"Use the #SEASONING+~PREP3# to #FOOD_PREP_3#, then #SERVE#",
			"When the #FOOD_PRODUCT+~PROD1# begins to #FINISHING#, #FOOD_PREP_3# and #SERVE#",
			"Assuming you're using a #COOKER+~COOK1#, watch the #FOOD_BASIC+~PREP1# until they start to #FINISHING#",
			""
			
	)),
	
	FINISHING(new PhraseList(
			"brown",
			"caramelise",
			"harden",
			"soften",
			"go green",
			"set",
			"wobble",
			"spread",
			w("emit noxious fumes", 0.25),
			"crack",
			"sing",
			w("scream", 0.25),
			"toast",
			""
			
	)),
	
	REC_H(new PhraseList(
			"#FOOD_PRODUCT+~PROD1+%CAP# - Edition #FOURTY_NUMBER#",
			"Creating lovely #SEASONING+~PROD1#",
			"Tasty #SEASONING+~PROD1#",
			"#FOOD_PRODUCT+~PROD1+%CAP# - Volume #FOURTY_NUMBER#",
			""
			
			
	)),
	
	
	
	SERVE(new PhraseList(
			"place decoratively on a platter",
			w("throw it on the ground", 0.1),
			"you are ready to go",
			"polish",
			"smile, #ADV#",
			"arrange appropriately",
			"serve to your party of #PEOPLE_PLURAL#",
			"leave to harden for a further #FOURTY_NUMBER# minutes",
			"leave to soften for a further #FOURTY_NUMBER# minutes",
			"leave to cool for a further #FOURTY_NUMBER# minutes",
			""
			
	)),
	
	
	SEASONING(new PhraseList(
			w("salt", 5.0),
			w("pepper", 4.0),
			"cayenne",
			"paprika",
			"seasoning",
			"toast",
			"grog",
			"chilli",
			"curry powder",
			"garlic",
			"redstone",
			"glowstone",
			"gunpowder",
			"matchsticks",
			"ducks",
			"lemon zest",
			"rosemary",
			"thyme",
			"cinnamon",
			"bayleaf",
			"artichoke hearts",
			"coriander",
			"mint",
			"extra strong #SEASONING#",
			"iron filings",
			"ghast tears",
			"magma cream",
			"nether wart",
			""
			
	)),
	
	
	
	
	
	
	
	SENT_A(new PhraseList(
			"News emerges that",
			"A story is circulating that",
			"It appears that",
			"It seems that",
			"According to sources,",
			"Apparently,",
			"Shockingly,",
			"Astoundingly,",
			"Oddly,",
			"Information has been brought to our attention that",
			""
			
	)),
	
	SENT_B(new PhraseList(
			"were discovered",
			"were seen",
			"have been seen",
			"were noticed",
			"were caught",
			"have been caught",
			"were arrested",
			"have been arrested",
			"were shot",
			"were #ADV#",
			"got in trouble after",
			"required assistance after",
			"called for help after",
			"requested police aid after",
			"shot at passers-by before",
			"insulted #TITLE_MALE# #NAMES_MALE_FIRST# before",
			"were brutally murdered after",
			"#ADV# incinerated a #NOUNS_BASIC#, before",
			"messed about with #NOUNS_BASIC_PLURAL#, before",
			""
	)),
	
	PEOPLE_PLURAL(new PhraseList(
			"idiots",
			"policemen",
			"firemen",
			"washerwomen",
			"fishermen",
			"mere-people",
			"#ANIMAL_PLURAL#",
			"peasants",
			"aid-workers",
			"foreign dignitaries",
			"telephone salesmen",
			"drunk party-goers",
			"celibate monks",
			"celibate nuns",
			"people",
			"#ANIMAL_SING# people",
			"politicians",
			"pilots",
			"soldiers",
			"pirates",
			"fascists",
			"communists",
			"#NOUNS_BASIC# salesmen",
			"tank-hunters",
			"#NOUNS_BASIC_PLURAL#",
			"#ANIMAL_SING#-handlers",
			"musicians",
			"pop-stars",
			"singers",
			"chimney-sweeps",
			"scientists",
			"hardcore gamers",
			"sportsmen",
			"sportswomen",
			"lumberjacks",
			""
			
			
			
	)),
	
	SENT_D(new PhraseList(
			"Sadly,",
			"Unfortunately,",
			"Disappointingly,",
			"Uncertain of the consequences,",
			"Rather stupidly,",
			"Amazingly,",
			"Happily,",
			"By order of the Law,",
			"It was during these shenanigans that",
			"In complete stupefaction, it has been suggested that",
			"#THE# #TITLE_MALE# of the Law insisted that",
			""
			
	)),
	
	OUTCOMES(new PhraseList(
			"shot for treason",
			"burnt at the stake",
			"#VERB_PAST# without trial",
			"#VERB_PAST# at great expense",
			"#VERB_PAST# immediately",
			"given a selection of #NOUNS_BASIC_PLURAL#",
			"devoured by #ANIMAL_PLURAL#",
			"laughed at by the populace",
			"#VERB_PAST#",
			"sacrificed to the Gods",
			"heralded heroically",
			"shunted sideways a few yards",
			"dropped down a deep hole",
			"thrown down the well",
			"eaten",
			"clobbered",
			"tasted",
			"incinerated",
			"battered thoroughly",
			"stroked gently",
			"invited to lunch",
			"invited to breakfast",
			"invited round for tea",
			"immolated",
			"seasoned",
			"shipped off-world",
			"ridiculed",
			"annihilated",
			"decimated",
			"hailed",
			"applauded",
			"rewarded",
			"employed full time",
			"given back-massages",
			""
	)),
	
	CONT_ADVERB_CAPS(new PhraseList(
			"However",
			"But",
			"Nevertheless",
			"Nonetheless",
			"Still",
			"Yet",
			"Although",
			"Even so",
			"For all that",
			"Despite this",
			"In spite of this",
			""
			
			
	)),
	
	TIMES_FUTURE(new PhraseList(
			"later",
			"tomorrow",
			"next week",
			"next year",
			"in due course",
			w("when one can be bothered", 0.25),
			"at a later date",
			"in time",
			"in a few hours",
			"in 31 minutes",
			"forthwith",
			"at lunchtime",
			"at dinnertime",
			w("after entropy has destroyed the cosmos", 0.25),
			"in a tick",
			"in several days",
			""
	)),
	
	TIMES_PAST(new PhraseList(
			"last week",
			"yesterday",
			"previously",
			"earlier",
			"last month",
			"last year",
			"in the last few days",
			"in the last few weeks",
			"in the last few years",
			"at a time before time",
			""
	
			
	)),
			
	
	THING(new PhraseList(
			"#NOUNS_BASIC#",
			"#ANIMAL_SING#",
			""
			
	)),
	
	THINGS(new PhraseList(
			"#NOUNS_BASIC_PLURAL#",
			"#PEOPLE_PLURAL#",
			"#ANIMAL_PLURAL#",
			""
	)),
	
	SENT_I(new PhraseList(
			"The #PEOPLE_PLURAL+~SUBJ1# ended up being #APPREHENDED#",
			"#CONT_ADVERB_CAPS# the #PEOPLE_PLURAL+~SUBJ1# and friends #ESCAPED# #WHERE+~DEST1#. #DESTOUT#",
			"After being #VERB_PAST+~OUT1#, the #PEOPLE_PLURAL+~SUBJ1# and several onlookers #INVOLVED2# in #CRIME#",
			"After being #VERB_PAST+~OUT1#, the #PEOPLE_PLURAL+~SUBJ1# and friends #ESCAPED# #PLACE_1+~P1+%CAP##PLACE_2+~P2#",
			"Having been #VERB_PAST+~OUT1#, #PEOPLE_PLURAL+~SUBJ2# accused #PEOPLE_PLURAL+~SUBJ1# of #CRIME#"
			
	)),
	
	
	DESTOUT(new PhraseList(
			"Upon arrival at #WHERE+~DEST1#, #CRIME# appeared to be the only thing on their minds",
			"After reaching #WHERE+~DEST1#, they #ADV# #ESCAPED# an unknown location",
			"Several #PEOPLE_PLURAL# #SAWPP# them #DESTOUT2# the scene"
			
	)),
	
	SAWPP(new PhraseList(
			"spotted",
			"saw",
			"spied",
			"noticed",
			"took note of",
			"recorded",
			"took surveillance of",
			""
			
	)),
	
	DESTOUT2(new PhraseList(
			"fleeing",
			"escaping",
			"running from",
			"legging it from",
			"making a get-away from",
			"playing football at",
			""
			
			
	)),
	
	
	CRIME(new PhraseList(
			"grand theft #THING#",
			"#THING# smuggling",
			"trafficking #PEOPLE_PLURAL#",
			"forgery of #NOUNS_BASIC_PLURAL#",
			"a number of crimes",
			"assaulting Mrs Beeton",
			"creating suspicious #FOOD_PRODUCT#",
			"a shocking display of #CRIME#",
			"a shocking display of #VERB_PRES#",
			"jousting",
			"dancing",
			"an #ADJ# display of #VERB_PRES#",
			"looting",
			"theft of #THINGS#",
			"kidnapping a#SIZE2# #ANIMAL_SING#",
			"making off with a#SIZE2# #NOUNS_BASIC#",
			""
			
			
			
	)),
	
	ESCAPED(new PhraseList(
			w("escaped to", 0.5),
			"made their way to",
			"secreted themselves in",
			"sieged their way to",
			"pillaged their way to",
			"abandoned ship in",
			"sacked their way to",
			"left the area, and headed to",
			"assumed control of",
			"invaded the centre of",
			"ran away, to",
			"liberated the heartlands of",
			""
			
	)),
	
	
	APPREHENDED(new PhraseList(
			w("arrested", 0.5),
			"detained",
			"caught",
			"interviewed by police",
			"cautioned",
			"given a sharp slap on the wrist",
			"tested for drugs",
			"allowed to walk free",
			"stabbed in the back",
			"told off",
			""
			
	)),
	
	SENT_J(new PhraseList(
			"a group of #PEOPLE_PLURAL+~SUBJ1# #SENT_B# engaging in #CRIME+~ACT1# in #PLACE_1+~P1+%CAP##PLACE_2+~P2#",
			"a#SIZE2# #ANIMAL_SING+~SUBJ1# was #OUTCOMES+~OUT1# by #THINGS+~SUBJ2# #TIMES_PAST#",
			"#TITLE_MALE+~SUBJ1# #NAMES_MALE_FIRST+~SUBJ1B# and #THEM+~SUBJ2# have been #OUTCOMES+~OUT1#",
			"#TITLE_FEMALE+~SUBJ1# #NAMES_FEMALE_FIRST+SUBJ1B# and #THEM+~SUBJ2# have been #OUTCOMES+~OUT1#",
			""
	)),
	
	SENT_K(new PhraseList(
			"#THINGS+%CAP# #INVOLVED#",
			"#THE+%CAP# outcome of this has caused the #THINGS+~SUBJ1# to be sent to #WHERE# #SENT_L#",
			"#THE+%CAP# resultant chain of events caused the #THINGS+~SUBJ1# to be sent to #WHERE# #SENT_L#",
			"Worryingly, the #THINGS+~SUBJ1# and fellow perpetrators have not been recovered",
			"#THEM+~SUBJ2+# declined to comment",
			""
	)),
	
	THEM(new PhraseList(
			"their family",
			"a group of #THINGS#",
			"faithful companion, #ANIMAL_SING#,",
			"their friends",
			"the populace of #PLACE_1+~P1+%CAP##PLACE_2+~P2#",
			"wife, #NAMETYPE#,",
			"husband, #NAMETYPE#,",
			""
	)),
	
	SENT_L(new PhraseList(
			"where they will be #OUTCOMES#",
			"to atone for their sins",
			"to serve the remainder of their sentence",
			"for #FOURTY_NUMBER# years",
			""
			
			
	)),
	
	
	A(new PhraseList(
		"a"	
	)),
	
	INVOLVED(new PhraseList(
			"may have been involved",
			"were certainly involved",
			"were most definitely not involved",
			"were involved",
			"were not involved",
			"can in no way have been involved",
			"are suspected of being involved",
			"should be considered involved",
			"are the perpetrators",
			"are the subject of an on-going investigation",
			"give rise for concern",
			"are being hunted down",
			"are wanted in connection with this event",
			"are to blame for this",
			"are very, very naughty",
			"should be avoided at all costs, due to the associated investigation",
			""
	)),
	
	INVOLVED2(new PhraseList(
			"may have been involved",
			"were certainly involved",
			"were most definitely not involved",
			"were involved",
			"were not involved",
			"can in no way have been involved",
			"are suspected of being involved",
			"should be considered involved",
			""
			
	)),
	
	
	WHERE(new PhraseList(
			w("a home", 0.5),
			"a school",
			"a secret place",
			"a safe place",
			"a hiding place",
			"an off-world destination",
			"a hole in the ground",
			"#PLACE_1+%CAP##PLACE_2#",
			"the residence of #TITLE_MALE# #NAMES_LAST#",
			"the residence of #TITLE_FEMALE# #NAMES_LAST#",
			"bed",
			"college",
			"university",
			"the North Pole",
			"the South Pole",
			"The End",
			"The Nether",
			"deep space",
			"a field",
			"a cosy cottage",
			"a cosy cottage in #PLACE_1+%CAP##PLACE_2#",
			"the top of a tree",
			"the top of mountain",
			"around 300 feet in the air",
			"a distant exoplanet",
			""
	)),
	
	TO(new PhraseList(
			"to"
			
	)),
	
	NAMETYPE(new PhraseList(
			w("#NAMES_MALE_FIRST+%CAP# #NAMES_LAST+%CAP#", 4.0),
			w("#NAMES_FEMALE_FIRST+%CAP# #NAMES_LAST+%CAP#", 4.0),
			"#TITLE_MALE+%CAP# #NAMES_MALE_FIRST+%CAP#",
			"#TITLE_FEMALE+%CAP# #NAMES_FEMALE_FIRST+%CAP#",
			"#TITLE_MALE+%CAP# #NAMES_LAST+%CAP#",
			"#TITLE_FEMALE+%CAP# #NAMES_LAST+%CAP#",
			"#TITLE_MALE+%CAP# #NAMES_MALE_FIRST+%CAP# #NAMES_LAST+%CAP#",
			"#TITLE_FEMALE+%CAP# #NAMES_FEMALE_FIRST+%CAP# #NAMES_LAST+%CAP#",
			w("#TITLE_MALE+%CAP# #NAMES_LAST+%CAP# #LAST_TITLE+%CAP#", 0.5),
			w("#TITLE_FEMALE+%CAP# #NAMES_LAST+%CAP# #LAST_TITLE+%CAP#", 0.5),
			w("#TITLE_MALE+%CAP# #NAMES_LAST+%CAP# the #ADJ+%CAP#", 0.5),
			w("#TITLE_FEMALE+%CAP# #NAMES_LAST+%CAP# the #ADJ+%CAP#", 0.5),
			w("#NAMES_MALE_FIRST+%CAP# #NAMES_LAST+%CAP# the #ADJ+%CAP# #ANIMAL_SING+%CAP#", 0.4),
			w("#NAMES_FEMALE_FIRST+%CAP# #NAMES_LAST+%CAP# the #ADJ+%CAP# #ANIMAL_SING+%CAP#", 0.4),
			w("#TITLE_MALE+%CAP# #NAMES_LAST+%CAP# the #ANIMAL_SING+%CAP#", 0.25),
			w("#TITLE_FEMALE+%CAP# #NAMES_LAST+%CAP# the #ANIMAL_SING+%CAP#", 0.25),
			w("#TITLE_MALE+%CAP# #NAMES_LAST+%CAP# the #ADV+%CAP# #ADJ+%CAP#", 0.2),
			w("#TITLE_FEMALE+%CAP# #NAMES_LAST+%CAP# the #ADV+%CAP# #ADJ+%CAP#", 0.2),
			"#NAMES_MALE_FIRST+%CAP#",
			"#NAMES_FEMALE_FIRST+%CAP#",
			"#ANIMAL_SING+%CAP# #NAMES_MALE_FIRST+%CAP#"
	)),
	
	TITLETYPE(new PhraseList(
			/*"#TITLE_MALE+%CAP# of the #ANIMAL_PLURAL+%CAP#",
			"#ADJ+%CAP# #MC_ITEM+%CAP#",
			"#ADJ+%CAP# #NOUNS_BASIC+%CAP#",
			"#ADJ+%CAP# Tales",
			"#BOOKTYPE# the #ANIMAL_PLURAL+%CAP# and #TITLE_MALE+%CAP# #NAMES_MALE_FIRST+%CAP#",
			"#TITLE_MALE+%CAP# #NAMES_MALE_FIRST+%CAP# and the #ADJ+%CAP# #NOUNS_BASIC+%CAP#",
			"#BOOKTYPE# #NOUNS_BASIC_PLURAL+%CAP#",
			"#BOOKTYPE# #ADJ+%CAP# #ANIMAL_PLURAL+%CAP#",
			"#TITLE_FEMALE+%CAP# #NAMES_LAST+%CAP# and the #NOUNS_BASIC+%CAP#",
			"#ADJ+%CAP#",
			"#ADJ+%CAP#!",
			"#ANIMAL_PLURAL+%CAP#",
			"#NOUNS_BASIC+%CAP# #NOUNS_BASIC+%CAP#",
			"#NOUNS_BASIC+%CAP# #NOUNS_BASIC+%CAP#!",
			"#ANIMAL_PLURAL+%CAP#... #EXCLAMATION+%CAP#!",
			"#NAMETYPE#'s #NOUNS_BASIC+%CAP#",
			"#NAMETYPE#'s #NOUNS_BASIC_PLURAL+%CAP#",
			"#ANIMAL_SING+%CAP# #NOUNS_BASIC_PLURAL+%CAP#",
			"#ANIMAL_SING+%CAP# #ANIMAL_PLURAL+%CAP#",
			"#ADJ+%CAP# #NOUNS_BASIC+%CAP#",
			"#NOUNS_BASIC+%CAP# #ANIMAL_SING+%CAP# and the #ADJ+%CAP# #TITLE_MALE+%CAP#",
			"#NOUNS_BASIC_PLURAL+%CAP# #BOOKTYPE_END#",
			"#ADV+%CAP# #ADJ+%CAP# #BOOKTYPE_END#",
			"#BOOKSTART_1# #NOUNS_BASIC_PLURAL+%CAP#",
			"#BOOKSTART_1# #VERB_PRES+%CAP# #NOUNS_BASIC_PLURAL+%CAP#",
			"#BOOKSTART_2# #VERB_PRES+%CAP# #NOUNS_BASIC_PLURAL+%CAP#",
			"#BOOKSTART_2# #ANIMAL_SING+%CAP# #VERB_PRES+%CAP#",
			"#TITLE_FEMALE+%CAP# #NAMES_FEMALE_FIRST+%CAP# on #VERB_PRES+%CAP# #NOUNS_BASIC_PLURAL+%CAP#",
			"#NAMES_MALE_FIRST#, on #VERB_PRES+%CAP#",
			"#BOOKSTART_1# #VERB_PAST+%CAP# #NOUNS_BASIC_PLURAL+%CAP#",
			"#VERB_PRES+%CAP# #FOOD_PRODUCT+%CAP#",
			"#BOOKTYPE# #NAMES_MALE_FIRST+%CAP# the #VERB_PRES+%CAP#",
			"#VERB_PRES+%CAP# Things #ADV+%CAP#",
			"#PRONOUN+%CAP# #VERB_PAST+%CAP# #PRONOUN_OBJ+%CAP#",
			"#VERB_PRES+%CAP# #NAMES_FEMALE_FIRST+%CAP#",
			"#VERB_PRES+%CAP# #TITLE_MALE+%CAP# #NAMES_MALE_FIRST+%CAP#",
			"#ADJ+%CAP# #NOUNS_BASIC+%CAP#, #ADJ+%CAP# #NOUNS_BASIC+%CAP#",
			"#ADJ+%CAP# #NOUNS_BASIC+%CAP#-#NOUNS_BASIC_PLURAL+%CAP#",
			"#ADJ+%CAP# #MC_BLOCK+%CAP#",
			"#PRONOUN+%CAP# #VERB_PAST+%CAP#",
			"#PRONOUN+%CAP# #VERB_PAST+%CAP# - It Was #ADJ+%CAP#",*/
			
			//Recipe Books
			
			"#RECIPE_BOOKTYPE# #FOOD_BASIC+~PREP1+%CAP# #FOOD_PRODUCT+~PROD1+%CAP@#",
			"#RECIPE_BOOKTYPE# #FOOD_PRIMARY+%CAP# #FOOD_BASIC+~PREP1+%CAP# #FOOD_PRODUCT+~PROD1+%CAP@#",
			"#RECIPE_BOOKTYPE# #FOOD_PRIMARY+%CAP# #ANIMAL_SING+~PREP1+%CAP# #FOOD_PRODUCT+~PROD1+%CAP@#",
			"#RECIPE_BOOKTYPE# #FOOD_BASIC+~PREP1+%CAP# and #ANIMAL_SING+~PREP2+%CAP# #FOOD_PRODUCT+~PROD1+%CAP@#",
			
			//Newspapers NEWS_TITLE_1 NEWS_TITLE_2 THE PLACE_1 PLACE_2
			
			"#THE+%CAP# #NEWS_TITLE_1+%CAP# #NEWS_TITLE_2+%CAP#",
			"#THE+%CAP# #PLACE_1+%CAP##PLACE_2# #NEWS_TITLE_2+%CAP#",
			"#THE+%CAP# #ANIMAL_SING+%CAP##PLACE_2# #NEWS_TITLE_2+%CAP#",
			"#THE+%CAP# #PLACE_1+%CAP##PLACE_2# #ANIMAL_SING+%CAP#",
			"#THE+%CAP# #PLACE_1+%CAP##PLACE_2# #NEWS_TITLE_2+%CAP#"
			
			//Hybrid
			
			/*"#THE+%CAP# #VERB_PRES+%CAP# at #PLACE_1+%CAP##PLACE_2#",
			"#THE+%CAP# #VERB_PRES+%CAP# at #ANIMAL_SING+%CAP##PLACE_2#",
			"#THE+%CAP# #VERB_PRES+%CAP# at #NOUNS_BASIC+%CAP##PLACE_2#",
			"#THE+%CAP# #VERB_PRES+%CAP#",
			"#BOOKTYPE# #PLACE_1+%CAP##PLACE_2#",
			"#BOOKTYPE# #FOOD_BASIC+%CAP##PLACE_2#",
			"#THE+%CAP# #VERB_PRES+%CAP# at #FOOD_PRODUCT+%CAP##PLACE_2#",
			"#NAMES_FIRST+%CAP# and the #ADJ+%CAP# #MC_ITEM+%CAP#"*/
			
	)),
	
	BOOKTYPE(new PhraseList(
			"The Tome of",
			"A Treatise on",
			"An Essay on",
			"A Diary of",
			"My Account of",
			"A Tale of",
			"The Story of",
			"My First-Hand Experience of",
			"An Exploration of",
			"The Collected Tales of",
			"An Anthology of",
			"The Almanack of"
	)),
	
	
	PRONOUN(new PhraseList(
			"I",
			"you",
			"he",
			"she",
			"it",
			"we",
			"they"
			
	)),
	
	PRONOUN_OBJ(new PhraseList(
			"me",
			"him",
			"her",
			"them",
			"it",
			"us"
			
			
	)),
	
	BOOKSTART_1(new PhraseList(
			"Why I Love",
			"My Thoughts on",
			"Man, I just love",
			"#EXCLAMATION+%CAP#! Look at These",
			"#ADJ+%CAP# #NAMES_FEMALE_FIRST# and the",
			"A Whole Load of",
			"He Bought Me",
			"She Bought Me",
			"There Were Only...",
			"#ADJ+%CAP#"
			
			
			
	)),
	
	BOOKSTART_2(new PhraseList(
			"A Manual on",
			"Introducing"
	)),
	
	BOOKTYPE_END(new PhraseList(
			"- Collected Tales",
			"- a Magazine for Collectors",
			"- the Tales Thereof"
			
			
	)),
	
	
	EXCLAMATION(new PhraseList(
			"Drat",
			"Bother",
			"Fiddlesticks",
			"Damnation",
			"Alas",
			"Alack",
			"Greeeeeeeeeg!?"
			
			
	)),
	
	NOUNS_BASIC(new PhraseList(
			"alumnus",
			"cactus",
			"focus",
			"fungus",
			"nucleus",
			"radius",
			"stimulus",
			"axis",
			"analysis",
			"crisis",
			"diagnosis",
			"ellipsis",
			"hypothesis",
			"oasis",
			"synopsis",
			"thesis",
			"child",
			"man",
			"woman",
			"bureau",
			"species",
			"time",
			"year",
			"people",
			"way",
			"day",
			"man",
			"thing",
			"life",
			"world",
			"school",
			"state of affairs",
			"state",
			"family",
			"student",
			"group",
			"country",
			"problem",
			"hand",
			"place",
			"case",
			"week",
			"company",
			"system",
			"program",
			"question",
			"work",
			"government",
			"number",
			"night",
			"point",
			"home",
			"water",
			"room",
			"mother",
			"area",
			"story",
			"month",
			"study",
			"book",
			"eye",
			"word",
			"business",
			"issue",
			"side",
			"kind",
			"head",
			"house",
			"service",
			"friend",
			"father",
			"game",
			"line",
			"end",
			w("member", 0.25),
			"law",
			"car",
			"city",
			"community",
			"name",
			"president",
			"team",
			"minute",
			"idea",
			"kid",
			"body",
			"information",
			"parent",
			"face",
			"others",
			"level",
			"office",
			"door",
			"health",
			"person",
			"art",
			"war",
			"history",
			"party",
			"result",
			"change",
			"morning",
			"reason",
			"research",
			"girl",
			"guy",
			"moment",
			"air",
			"teacher",
			"force",
			"education",
			"home",
			"trail",
			"powder",
			"lake",
			"cover",
			"trail",
			"tin",
			"bedroom",
			"plot",
			"pet",
			"lumber",
			"circle",
			"club",
			"worm",
			"afterthought",
			"twig",
			"eye",
			"floor",
			"language",
			"position",
			"seashore",
			"destruction",
			"flight",
			"pipe",
			"belief",
			"art",
			"neck",
			"button",
			"wave",
			"toy",
			"picture",
			"button",
			"lunch",
			"tail",
			"camp",
			"middle",
			"veil",
			"fireman",
			"note",
			"rhythm",
			"apparel",
			"whistle",
			"boot",
			"creature",
			"birth",
			"friction",
			"slave",
			"mass",
			"form",
			"vase",
			"scarf",
			"instrument",
			"sun",
			"linen",
			"shoe",
			"feeling",
			"station",
			"army",
			"hydrant",
			"glass",
			"knowledge",
			"tank",
			"bush",
			"worm",
			"pest",
			"respect",
			"guitar",
			"piano",
			"base",
			"stove",
			"theory",
			"railway",
			"zipper",
			"hate",
			"dock",
			"authority",
			"sand",
			"yard",
			"stranger",
			"corn",
			"jelly",
			"eggnog",
			"wire",
			"partner",
			"argument",
			"experience",
			"reward",
			"thumb",
			"wood",
			"condition"

	
			
			
	)),
	
	NOUNS_BASIC_PLURAL(new PhraseList(
			"alumni",
			"cacti",
			"foci",
			"fungi",
			"nuclei",
			"radii",
			"stimuli",
			"axes",
			"analyses",
			"crises",
			"diagnoses",
			"ellipses",
			"hypotheses",
			"oases",
			"synopses",
			"theses",
			"children",
			"men",
			"women",
			"bureaus",
			"species",
			"times",
			"years",
			"people",
			"ways",
			"days",
			"things",
			"lives",
			"worlds",
			"schools",
			"states of affairs",
			"states",
			"families",
			"students",
			"groups",
			"countries",
			"problems",
			"hands",
			"places",
			"cases",
			"weeks",
			"companies",
			"systems",
			"programs",
			"questions",
			"works",
			"governments",
			"numbers",
			"nights",
			"points",
			"homes",
			"waters",
			"rooms",
			"mothers",
			"areas",
			"stories",
			"months",
			"studies",
			"books",
			"eyes",
			"words",
			"businesses",
			"issues",
			"sides",
			"heads",
			"houses",
			"services",
			"friends",
			"fathers",
			"games",
			"lines",
			"ends",
			"members",
			"laws",
			"cars",
			"cities",
			"communities",
			"names",
			"presidents",
			"teams",
			"minutes",
			"ideas",
			"kids",
			"bodies",
			"information",
			"parents",
			"faces",
			"others",
			"levels",
			"offices",
			"doors",
			"health",
			"arts",
			"wars",
			"histories",
			"parties",
			"results",
			"changes",
			"mornings",
			"reasons",
			"researches",
			"girls",
			"guys",
			"moments",
			"air",
			"teachers",
			"forces",
			"educations",
			"homes",
			"trails",
			"powders",
			"lakes",
			"covers",
			"trails",
			"tins",
			"bedrooms",
			"plots",
			"pets",
			"lumber",
			"circles",
			"clubs",
			"worms",
			"afterthoughts",
			"twigs",
			"eyes",
			"floors",
			"languages",
			"positions",
			"seashores",
			"destruction",
			"flights",
			"pipes",
			"beliefs",
			"arts",
			"necks",
			"buttons",
			"waves",
			"toys",
			"pictures",
			"buttons",
			"lunches",
			"tails",
			"camps",
			"middles",
			"veils",
			"firemen",
			"notes",
			"rhythms",
			"apparel",
			"whistles",
			"boots",
			"creatures",
			"births",
			"friction",
			"slaves",
			"masses",
			"forms",
			"vases",
			"scarves",
			"instruments",
			"suns",
			"linen",
			"shoes",
			"feelings",
			"stations",
			"armies",
			"hydrants",
			"glasses",
			"knowledge",
			"tanks",
			"bushes",
			"worms",
			"pests",
			"respects",
			"guitars",
			"pianos",
			"bases",
			"stoves",
			"theories",
			"railways",
			"zippers",
			"hates",
			"docks",
			"authorities",
			"sands",
			"yards",
			"strangers",
			"corns",
			"jellies",
			"eggnogs",
			"wires",
			"partners",
			"arguments",
			"experiences",
			"rewards",
			"thumbs",
			"woods",
			"conditions",
			"planes"
			
			
	)),
	
	NAMES_MALE_FIRST(new PhraseList(
			"Slowpoke",
			"Runewolf",
			"Direwolf",
			"Soaryn",
			"Pahimar",
			"Bill",
			"Dave",
			"Harry",
			"David",
			"Harold",
			"Swifty",
			"Cletus",
			"Bobbin",
			"Phil",
			"Tremendo",
			"Robert",
			"Roberto",
			"Blackbeard",
			"Terry",
			"Hank",
			"Viscero",
			"Ted",
			"Alexander",
			"Arheo",
			"Bleebus",
			"Rocco",
			"Henchfist",
			"Virgil",
			"Stewart",
			"Bellybelly",
			"Grimnose",
			"Luke",
			"Lucas",
			"Nicholas",
			"Nick",
			"Philip",
			"Peter",
			"Phillipus",
			"Stanley",
			"Stan",
			"Toad",
			"Brewbags",
			"Abraham",
			"Abe",
			"Adam",
			"Solomon",
			"Han",
			"Flash",
			"James",
			"Tiberius",
			"Bruce",
			"Boris",
			"Romeo",
			"Ken",
			"Steve",
			"Tannenbaum",
			"Optimus",
			"Daniel",
			"Sam",
			"Samuel",
			"Andreas",
			"Bladetoes",
			"Grumbleguts",
			"Donatello",
			"Andy",
			"Blump",
			"Stegasaurus",
			"John",
			"Spannerhands",
			"Keith",
			"Don",
			"Fantastico",
			"Lewis",
			"Matthew",
			"Matt",
			"Brick",
			"Barrelhands",
			"Sweevil",
			"Aluminium",
			"Ironpants",
			"Trousersoul",
			"Fish-Eyes",
			"Benedict",
			"John-Paul",
			"Paul",
			"Paulus",
			"Innocentius",
			w("Jesus",0.1),
			"Fernando",
			"Mario",
			"Luigi",
			"Pimlico",
			"Jack",
			"Oliver",
			"Charlie",
			"Alfie",
			"Noah",
			"Oscar",
			"George",
			"Leo",
			"William",
			"Joshua",
			"Logan",
			"Freddie",
			"Archie",
			"Max",
			"Henry",
			"Ethan",
			"Lucas",
			"Joseph",
			"Jake",
			"Harrison",
			"Benjamin",
			"Toby",
			"Ollie",
			"Harvey",
			"Blake",
			"Nathan",
			"Callum",
			"Aaron",
			"Elijah",
			"Hugo",
			"Rory",
			"Leon",
			"Reuben",
			"Evan",
			"Seth",
			"Caleb",
			"Jackson",
			"Austin",
			"Ellis",
			"Bayley",
			"Bayle",
			"Kyle",
			"Zack",
			"Ronnie",
			"Dexter"
	)),
	
	NAMES_FEMALE_FIRST(new PhraseList(
			"Jellybean",
			"Morvelaira",
			"Rorax",
			"Kleetho",
			"Aurelian",
			"Minalien",
			"Imalune",
			"Billis",
			"Davina",
			"Harriet",
			"Daniella",
			"Danni",
			"Arianna",
			"Henrietta",
			"Plumpus",
			"Isabel",
			"Indigo",
			"Leominster",
			"Amanda",
			"Amaryllis",
			"Amala",
			"Kate",
			"Katherine",
			"Cait",
			"Elizabeth",
			"Horror-Hands",
			"Elspeth",
			"Margaret",
			"Repentia",
			"Penitentia",
			"Liara",
			"Lia",
			"Logosphericus",
			"Turnip",
			"Sally",
			"Splendidia",
			"Grace",
			"Ava",
			"Amelia",
			"Rose",
			"Rosemary",
			"Rosie",
			"Janet",
			"Gianetta",
			"Deborah",
			"Sockflower",
			"Louise",
			"Steve",
			"Esmerelda",
			"Elinor",
			"Amy",
			"Burgerette",
			"Slitherchops",
			"Snake-Eyes",
			"Slimer",
			"Pansy",
			"Daisy",
			"Tulip",
			"Crabapple",
			"Gourd-Tree",
			"Georgette",
			"Anna",
			"Annabelle",
			"Belle",
			"Rotary-Head",
			"Lucy",
			"Kathryn",
			"Olivia",
			"Olive",
			"Juliet",
			"Julie",
			"Siena",
			"Mercedes",
			"Piper",
			"Elise",
			"Portia",
			"Wine-Carton",
			"Minnie",
			"Xynthia",
			"Cleopatra",
			"Jezebel",
			"Whiskers",
			"Augusta",
			"April",
			"June",
			"October",
			"Beef",
			"Sophia",
			"Emma",
			"Olivia",
			"Isabella",
			"Mia",
			"Zoe",
			"Lily",
			"Emily",
			"Layla",
			"Charlotte",
			"Madison",
			"Hannah",
			"Abigail",
			"Amelia",
			"Riley",
			"Aria",
			"Evelyn",
			"Brooklyn",
			"Claire",
			"Gabriella",
			"Kennedy",
			"Sadie",
			"Allison",
			"Caroline",
			"Charlie",
			"Violet",
			"Adeline",
			"Keira",
			"Alexandra",
			"Camilla",
			"Alexis",
			"Lauren",
			"Bella",
			"Clara",
			"Julia",
			"Stella",
			"Agatha",
			"Augusta",
			"Aurora",
			"Beatrice",
			"Bertha",
			"Margery",
			"Vera",
			"Cician",
			"Rosalind",
			"Prudence",
			"Priscilla",
			"Lottie",
			"Genevieve",
			"Gwyneth",
			"Fay",
			"Elaine",
			"Celia",
			"Beryl",
			"Susan"
			
	)),
	
	NAMES_FIRST(new PhraseList(
			"#NAMES_MALE_FIRST#",
			"#NAMES_FEMALE_FIRST#"
	)),
	
	NAMES_LAST(new PhraseList(
			"Billo",
			"Davo",
			"Haricot Verts",
			"Trump",
			"Blump",
			"Flump",
			"Tyre-Iron",
			"Rubberpants",
			"Bottle",
			"Carter",
			"Lager-Brute",
			"Stefanov",
			"Spaniel",
			"Labrador",
			"Rhinoceros-Features",
			"Spiniksissius",
			"Whitacre",
			"Phelps",
			"Bleasby",
			"Potter",
			"Rothschild",
			"Fandlebrough",
			"Banderbie",
			"Raccoon",
			"Frith",
			"Filthsack",
			"Adams",
			"James",
			"Bond",
			"Bonnet",
			"Toughnall",
			"Tuffnell",
			"Tunneldweller",
			"Blenkinsop",
			"Cadderby",
			"Gadsby",
			"Lewisham",
			"Spingle",
			"Blimp",
			"Stewart",
			"Urist",
			"Von Bonjela",
			"Van Beethoven",
			"Bach",
			"Marcioni",
			"Machiavelli",
			"Palletfists",
			"Lestat",
			"Hollis",
			"Hollins",
			"Harley",
			"Finkelstein",
			"Winkelstein",
			"Pinkelstein",
			"Frankenstein",
			"Drago",
			"Drogo",
			"Baggins",
			"Butler",
			"Halfyard",
			"Halfmast",
			"Saint",
			"Sweelinck",
			"Nyckolszoon",
			"Blenkinsneff",
			"Spiderpants",
			"Legsakimbo",
			"Wayne",
			"Rayne",
			"Smiler",
			"Rambunctio",
			"Rambo",
			"Hambo",
			"Limpus",
			"Limpet-Mine",
			"Manhands",
			"Slitherlegs",
			"Arturo",
			"Arcturus",
			"Slamdunkle",
			"Hogan",
			"Forbes",
			"Forsyth",
			"Brand",
			"Brandle",
			"Henderson",
			"Menderson",
			"Mandelbrot",
			"Dragonbreath",
			"Pillsborough",
			"Wooster",
			"Jeeves",
			"Finnegan",
			"Flanegan",
			"O'Mairi",
			"Myrtlebest",
			"Best",
			"Wurst",
			"Stew",
			"Crimsoneyes",
			"Nostrum",
			"Balls",
			"Barnes",
			"Abrams",
			"Bostwick",
			"Howland",
			"McMullen",
			"Monroe",
			"Crumpacker",
			"Winkler",
			"Van Winkle",
			"Kirk",
			"Van Kirk",
			"Spock",
			"Sykes",
			"Spencer",
			"Gilkey",
			"Gaston",
			"Galloway",
			"Schwarz",
			"Fletcher",
			"Fuller",
			"Pinkerton",
			"Pearson",
			"Connell",
			"o'Connell",
			"Coates",
			"Brown",
			"Bland",
			"Dobson",
			"Ballard",
			"Barrett",
			"Keenan",
			"Jacobson",
			"Anderson",
			"Jones",
			"Newland",
			"Maynard"

	
	)),
	
	VERB(new PhraseList(
			"accept",
			"add",
			"admire",
			"admit",
			"advise",
			"afford",
			"agree",
			"alert",
			"allow",
			"amuse",
			"analyse",
			"announce",
			"annoy",
			"answer",
			"apologise",
			"appear",
			"applaud",
			"appreciate",
			"approve",
			"argue",
			"arrange",
			"arrest",
			"arrive",
			"ask",
			"attach",
			"attack",
			"attempt",
			"attend",
			"attract",
			"avoid",
			"back",
			"bake",
			"balance",
			"ban",
			"bang",
			"bare",
			"bat",
			"bathe",
			"battle",
			"beam",
			"beg",
			"behave",
			"belong",
			"bleach",
			"bless",
			"blind",
			"blink",
			"blot",
			"blush",
			"boast",
			"boil",
			"bolt",
			"bomb",
			"book",
			"bore",
			"borrow",
			"bounce",
			"bow",
			"box",
			"brake",
			"branch",
			"breathe",
			"bruise",
			"brush",
			"bubble",
			"bump",
			"burn",
			"bury",
			"buzz",
			"calculate",
			"call",
			"camp",
			"care",
			"carry",
			"carve",
			"cause",
			"challenge",
			"change",
			"charge",
			"chase",
			"cheat",
			"check",
			"cheer",
			"chew",
			"choke",
			"chop",
			"claim",
			"clap",
			"clean",
			"clear",
			"clip",
			"close",
			"coach",
			"coil",
			"collect",
			"colour",
			"comb",
			"command",
			"communicate",
			"compare",
			"compete",
			"complain",
			"complete",
			"concentrate",
			"concern",
			"confess",
			"confuse",
			"connect",
			"consider",
			"consist",
			"contain",
			"continue",
			"copy",
			"correct",
			"cough",
			"count",
			"cover",
			"crack",
			"crash",
			"crawl",
			"cross",
			"crush",
			"cry",
			"cure",
			"curl",
			"curve",
			"cycle",
			"damage",
			"dance",
			"dare",
			"decay",
			"deceive",
			"decide",
			"decorate",
			"delay",
			"delight",
			"deliver",
			"depend",
			"describe",
			"desert",
			"deserve",
			"destroy",
			"detect",
			"develop",
			"disagree",
			"disappear",
			"disapprove",
			"disarm",
			"discover",
			"dislike",
			"divide",
			"double",
			"doubt",
			"drag",
			"drain",
			"dream",
			"dress",
			"drip",
			"drop",
			"drown",
			"drum",
			"dry",
			"dust",
			"earn",
			"educate",
			"embarrass",
			"employ",
			"empty",
			"encourage",
			"end",
			"enjoy",
			"enter",
			"entertain",
			"escape",
			"examine",
			"excite",
			"excuse",
			"exercise",
			"exist",
			"expand",
			"expect",
			"explain",
			"explode",
			"extend",
			"face",
			"fade",
			"fail",
			"fancy",
			"fasten",
			"fax",
			"fear",
			"fence",
			"fetch",
			"file",
			"fill",
			"film",
			"fire",
			"fit",
			"fix",
			"flap",
			"flash",
			"float",
			"flood",
			"flow",
			"flower",
			"fold",
			"follow",
			"fool",
			"force",
			"form",
			"found",
			"frame",
			"frighten",
			"fry",
			"gather",
			"gaze",
			"glow",
			"glue",
			"grab",
			"grate",
			"grease",
			"greet",
			"grin",
			"grip",
			"groan",
			"guarantee",
			"guard",
			"guess",
			"guide",
			"hammer",
			"hand",
			"handle",
			"hang",
			"happen",
			"harass",
			"harm",
			"hate",
			"haunt",
			"head",
			"heal",
			"heap",
			"heat",
			"help",
			"hook",
			"hop",
			"hope",
			"hover",
			"hug",
			"hum",
			"hunt",
			"hurry",
			"identify",
			"ignore",
			"imagine",
			"impress",
			"improve",
			"include",
			"increase",
			"influence",
			"inform",
			"inject",
			"injure",
			"instruct",
			"intend",
			"interest",
			"interfere",
			"interrupt",
			"introduce",
			"invent",
			"invite",
			"irritate",
			"itch",
			"jail",
			"jam",
			"jog",
			"join",
			"joke",
			"judge",
			"juggle",
			"jump",
			"kick",
			"kill",
			"kiss",
			"kneel",
			"knit",
			"knock",
			"knot",
			"label",
			"land",
			"last",
			"laugh",
			"launch",
			"learn",
			"level",
			"license",
			"lick",
			"lie",
			"lighten",
			"like",
			"list",
			"listen",
			"live",
			"load",
			"lock",
			"long",
			"look",
			"love",
			"man",
			"manage",
			"march",
			"mark",
			"marry",
			"match",
			"mate",
			"matter",
			"measure",
			"meddle",
			"melt",
			"memorise",
			"mend",
			"mess up",
			"milk",
			"mine",
			"miss",
			"mix",
			"moan",
			"moor",
			"mourn",
			"move",
			"muddle",
			"mug",
			"multiply",
			"murder",
			"nail",
			"name",
			"need",
			"nest",
			"nod",
			"note",
			"notice",
			"number",
			"obey",
			"object",
			"observe",
			"obtain",
			"occur",
			"offend",
			"offer",
			"open",
			"order",
			"overflow",
			"owe",
			"own",
			"pack",
			"paddle",
			"paint",
			"park",
			"part",
			"pass",
			"paste",
			"pat",
			"pause",
			"peck",
			"pedal",
			"peel",
			"peep",
			"perform",
			"permit",
			"phone",
			"pick",
			"pinch",
			"pine",
			"place",
			"plan",
			"plant",
			"play",
			"please",
			"plug",
			"point",
			"poke",
			"polish",
			"pop",
			"possess",
			"post",
			"pour",
			"practice",
			"pray",
			"preach",
			"precede",
			"prefer",
			"prepare",
			"present",
			"preserve",
			"press",
			"pretend",
			"prevent",
			"prick",
			"print",
			"produce",
			"program",
			"promise",
			"protect",
			"provide",
			"pull",
			"pump",
			"punch",
			"puncture",
			"punish",
			"push",
			"question",
			"queue",
			"race",
			"radiate",
			"rain",
			"raise",
			"reach",
			"realise",
			"receive",
			"recognise",
			"record",
			"reduce",
			"reflect",
			"refuse",
			"regret",
			"reign",
			"reject",
			"rejoice",
			"relax",
			"release",
			"rely",
			"remain",
			"remember",
			"remind",
			"remove",
			"repair",
			"repeat",
			"replace",
			"reply",
			"report",
			"reproduce",
			"request",
			"rescue",
			"retire",
			"return",
			"rhyme",
			"rinse",
			"risk",
			"rob",
			"rock",
			"roll",
			"rot",
			"rub",
			"ruin",
			"rule",
			"rush",
			"sack",
			"sail",
			"satisfy",
			"save",
			"saw",
			"scare",
			"scatter",
			"scold",
			"scorch",
			"scrape",
			"scratch",
			"scream",
			"screw",
			"scribble",
			"scrub",
			"seal",
			"search",
			"separate",
			"serve",
			"settle",
			"shade",
			"share",
			"shave",
			"shelter",
			"shiver",
			"shock",
			"shop",
			"shrug",
			"sigh",
			"sign",
			"signal",
			"sin",
			"sip",
			"ski",
			"skip",
			"slap",
			"slip",
			"slow",
			"smash",
			"smell",
			"smile",
			"smoke",
			"snatch",
			"sneeze",
			"sniff",
			"snore",
			"snow",
			"soak",
			"soothe",
			"sound",
			"spare",
			"spark",
			"sparkle",
			"spell",
			"spill",
			"spoil",
			"spot",
			"spray",
			"sprout",
			"squash",
			"squeak",
			"squeal",
			"squeeze",
			"stain",
			"stamp",
			"stare",
			"start",
			"stay",
			"steer",
			"step",
			"stir",
			"stitch",
			"stop",
			"store",
			"strap",
			"strengthen",
			"stretch",
			"strip",
			"stroke",
			"stuff",
			"subtract",
			"succeed",
			"suck",
			"suffer",
			"suggest",
			"suit",
			"supply",
			"support",
			"suppose",
			"surprise",
			"surround",
			"suspect",
			"suspend",
			"switch",
			"talk",
			"tame",
			"tap",
			"taste",
			"tease",
			"telephone",
			"tempt",
			"terrify",
			"test",
			"thank",
			"thaw",
			"tick",
			"tickle",
			"tie",
			"time",
			"tip",
			"tire",
			"touch",
			"tour",
			"tow",
			"trace",
			"trade",
			"train",
			"transport",
			"trap",
			"travel",
			"treat",
			"tremble",
			"trick",
			"trip",
			"trot",
			"trouble",
			"trust",
			"try",
			"tug",
			"tumble",
			"turn",
			"twist",
			"type",
			"undress",
			"unfasten",
			"unite",
			"unlock",
			"unpack",
			"untidy",
			"use",
			"vanish",
			"visit",
			"wail",
			"wait",
			"walk",
			"wander",
			"want",
			"warm",
			"warn",
			"wash",
			"waste",
			"watch",
			"water",
			"wave",
			"weigh",
			"welcome",
			"whine",
			"whip",
			"whirl",
			"whisper",
			"whistle",
			"wink",
			"wipe",
			"wish",
			"wobble",
			"wonder",
			"work",
			"worry",
			"wrap",
			"wreck",
			"wrestle",
			"wriggle",
			"x-ray",
			"yawn",
			"yell",
			"zip",
			"zoom"
	
	
	
	)),
	
	VERB_PAST(new PhraseList(
			"accepted",
			"added",
			"admired",
			"admitted",
			"advised",
			"afforded",
			"agreed",
			"alerted",
			"allowed",
			"amused",
			"analysed",
			"announced",
			"annoyed",
			"answered",
			"apologised",
			"appeared",
			"applauded",
			"appreciated",
			"approved",
			"argued",
			"arranged",
			"arrested",
			"arrived",
			"asked",
			"attached",
			"attacked",
			"attempted",
			"attended",
			"attracted",
			"avoided",
			"backed",
			"baked",
			"balanced",
			"banned",
			"banged",
			"bared",
			"batted",
			"bathed",
			"battled",
			"beamed",
			"begged",
			"behaved",
			"belonged",
			"bleached",
			"blessed",
			"blinded",
			"blinked",
			"blotted",
			"blushed",
			"boasted",
			"boiled",
			"bolted",
			"bombed",
			"booked",
			"bored",
			"borrowed",
			"bounced",
			"bowed",
			"boxed",
			"braked",
			"branched",
			"breathed",
			"bruised",
			"brushed",
			"bubbled",
			"bumped",
			"burned",
			"buried",
			"buzzed",
			"calculated",
			"called",
			"camped",
			"cared",
			"carried",
			"carved",
			"caused",
			"challenged",
			"changed",
			"charged",
			"chased",
			"cheated",
			"checked",
			"cheered",
			"chewed",
			"choked",
			"chopped",
			"claimed",
			"clapped",
			"cleaned",
			"cleared",
			"clipped",
			"closed",
			"coached",
			"coiled",
			"collected",
			"coloured",
			"combed",
			"commanded",
			"communicated",
			"compared",
			"competed",
			"complained",
			"completed",
			"concentrated",
			"concerned",
			"confessed",
			"confused",
			"connected",
			"considered",
			"consisted",
			"contained",
			"continued",
			"copied",
			"corrected",
			"coughed",
			"counted",
			"covered",
			"cracked",
			"crashed",
			"crawled",
			"crossed",
			"crushed",
			"cried",
			"cured",
			"curled",
			"curved",
			"cycled",
			"damaged",
			"danced",
			"dared",
			"decayed",
			"deceived",
			"decided",
			"decorated",
			"delayed",
			"delighted",
			"delivered",
			"depended",
			"described",
			"deserted",
			"deserved",
			"destroyed",
			"detected",
			"developed",
			"disagreed",
			"disappeared",
			"disapproved",
			"disarmed",
			"discovered",
			"disliked",
			"divided",
			"doubled",
			"doubted",
			"dragged",
			"drained",
			"dreamed",
			"dressed",
			"dripped",
			"dropped",
			"drowned",
			"drummed",
			"dried",
			"dusted",
			"earned",
			"educated",
			"embarrassed",
			"employed",
			"emptied",
			"encouraged",
			"ended",
			"enjoyed",
			"entered",
			"entertained",
			"escaped",
			"examined",
			"excited",
			"excused",
			"exercised",
			"existed",
			"expanded",
			"expected",
			"explained",
			"exploded",
			"extended",
			"faced",
			"faded",
			"failed",
			"fancied",
			"fastened",
			"faxed",
			"feared",
			"fenced",
			"fetched",
			"filed",
			"filled",
			"filmed",
			"fired",
			"fitted",
			"fixed",
			"flapped",
			"flashed",
			"floated",
			"flooded",
			"flowed",
			"flowered",
			"folded",
			"followed",
			"fooled",
			"forced",
			"formed",
			"founded",
			"framed",
			"frightened",
			"fried",
			"gathered",
			"gazed",
			"glowed",
			"glued",
			"grabbed",
			"grated",
			"greased",
			"greeted",
			"grinned",
			"gripped",
			"groaned",
			"guaranteed",
			"guarded",
			"guessed",
			"guided",
			"hammered",
			"handed",
			"handled",
			"hanged",
			"happened",
			"harassed",
			"harmed",
			"hated",
			"haunted",
			"headed",
			"healed",
			"heaped",
			"heated",
			"helped",
			"hooked",
			"hopped",
			"hoped",
			"hovered",
			"hugged",
			"hummed",
			"hunted",
			"hurried",
			"identified",
			"ignored",
			"imagined",
			"impressed",
			"improved",
			"included",
			"increased",
			"influenced",
			"informed",
			"injected",
			"injured",
			"instructed",
			"intended",
			"interested",
			"interfered",
			"interrupted",
			"introduced",
			"invented",
			"invited",
			"irritated",
			"itched",
			"jailed",
			"jammed",
			"jogged",
			"joined",
			"joked",
			"judged",
			"juggled",
			"jumped",
			"kicked",
			"killed",
			"kissed",
			"knelt",
			"knitted",
			"knocked",
			"knotted",
			"labelled",
			"landed",
			"lasted",
			"laughed",
			"launched",
			"learned",
			"levelled",
			"licensed",
			"licked",
			"lay",
			"lightened",
			"liked",
			"listed",
			"listened",
			"lived",
			"loaded",
			"locked",
			"longed",
			"looked",
			"loved",
			"manned",
			"managed",
			"marched",
			"marked",
			"married",
			"matched",
			"mated",
			"mattered",
			"measured",
			"meddled",
			"melted",
			"memorised",
			"mended",
			"messed up",
			"milked",
			"mined",
			"missed",
			"mixed",
			"moaned",
			"moored",
			"mourned",
			"moved",
			"muddled",
			"mugged",
			"multiplied",
			"murdered",
			"nailed",
			"named",
			"needed",
			"nested",
			"nodded",
			"noted",
			"noticed",
			"numbered",
			"obeyed",
			"objected",
			"observed",
			"obtained",
			"occurred",
			"offended",
			"offered",
			"opened",
			"ordered",
			"overflowed",
			"owed",
			"owned",
			"packed",
			"paddled",
			"painted",
			"parked",
			"parted",
			"passed",
			"pasted",
			"patted",
			"paused",
			"pecked",
			"pedalled",
			"peeled",
			"peeped",
			"performed",
			"permitted",
			"phoned",
			"picked",
			"pinched",
			"pined",
			"placed",
			"planned",
			"planted",
			"played",
			"pleased",
			"plugged",
			"pointed",
			"poked",
			"polished",
			"popped",
			"possessed",
			"posted",
			"poured",
			"practised",
			"prayed",
			"preached",
			"preceded",
			"preferred",
			"prepared",
			"presented",
			"preserved",
			"pressed",
			"pretended",
			"prevented",
			"pricked",
			"printed",
			"produced",
			"programmed",
			"promised",
			"protected",
			"provided",
			"pulled",
			"pumped",
			"punched",
			"punctured",
			"punished",
			"pushed",
			"questioned",
			"queued",
			"raced",
			"radiated",
			"rained",
			"raised",
			"reached",
			"realised",
			"received",
			"recognised",
			"recorded",
			"reduced",
			"reflected",
			"refused",
			"regretted",
			"reigned",
			"rejected",
			"rejoiced",
			"relaxed",
			"released",
			"relied",
			"remained",
			"remembered",
			"reminded",
			"removed",
			"repaired",
			"repeated",
			"replaced",
			"replied",
			"reported",
			"reproduced",
			"requested",
			"rescued",
			"retired",
			"returned",
			"rhymed",
			"rinsed",
			"risked",
			"robbed",
			"rocked",
			"rolled",
			"rotted",
			"rubbed",
			"ruined",
			"ruled",
			"rushed",
			"sacked",
			"sailed",
			"satisfied",
			"saved",
			"sawed",
			"scared",
			"scattered",
			"scolded",
			"scorched",
			"scraped",
			"scratched",
			"screamed",
			"screwed",
			"scribbled",
			"scrubbed",
			"sealed",
			"searched",
			"separated",
			"served",
			"settled",
			"shaded",
			"shared",
			"shaved",
			"sheltered",
			"shivered",
			"shocked",
			"shopped",
			"shrugged",
			"sighed",
			"signed",
			"signalled",
			"sinned",
			"sipped",
			"skied",
			"skipped",
			"slapped",
			"slipped",
			"slowed",
			"smashed",
			"smelled",
			"smiled",
			"smoked",
			"snatched",
			"sneezed",
			"sniffed",
			"snored",
			"snowed",
			"soaked",
			"soothed",
			"sounded",
			"spared",
			"sparked",
			"sparkled",
			"spelled",
			"spilled",
			"spoiled",
			"spotted",
			"sprayed",
			"sprouted",
			"squashed",
			"squeaked",
			"squealed",
			"squeezed",
			"stained",
			"stamped",
			"stared",
			"started",
			"stayed",
			"steered",
			"stepped",
			"stirred",
			"stitched",
			"stopped",
			"stored",
			"strapped",
			"strengthened",
			"stretched",
			"stripped",
			"stroked",
			"stuffed",
			"subtracted",
			"succeeded",
			"sucked",
			"suffered",
			"suggested",
			"suited",
			"supplied",
			"supported",
			"supposed",
			"surprised",
			"surrounded",
			"suspected",
			"suspended",
			"switched",
			"talked",
			"tamed",
			"tapped",
			"tasted",
			"teased",
			"telephoned",
			"tempted",
			"terrified",
			"tested",
			"thanked",
			"thawed",
			"ticked",
			"tickled",
			"tied",
			"timed",
			"tipped",
			"tired",
			"touched",
			"toured",
			"towed",
			"traced",
			"traded",
			"trained",
			"transported",
			"trapped",
			"traveled",
			"treated",
			"trembled",
			"tricked",
			"tripped",
			"trotted",
			"troubled",
			"trusted",
			"tried",
			"tugged",
			"tumbled",
			"turned",
			"twisted",
			"typed",
			"undressed",
			"unfastened",
			"united",
			"unlocked",
			"unpacked",
			"untidied",
			"used",
			"vanished",
			"visited",
			"wailed",
			"waited",
			"walked",
			"wandered",
			"wanted",
			"warmed",
			"warned",
			"washed",
			"wasted",
			"watched",
			"watered",
			"waved",
			"weighed",
			"welcomed",
			"whined",
			"whipped",
			"whirled",
			"whispered",
			"whistled",
			"winked",
			"wiped",
			"wished",
			"wobbled",
			"wondered",
			"worked",
			"worried",
			"wrapped",
			"wrecked",
			"wrestled",
			"wriggled",
			"x-rayed",
			"yawned",
			"yelled",
			"zipped",
			"zoomed"
			
			
	)),
	
	VERB_PRES(new PhraseList(
			"accepting",
			"adding",
			"admiring",
			"admitting",
			"advising",
			"affording",
			"agreeing",
			"alerting",
			"allowing",
			"amusing",
			"analysing",
			"announcing",
			"annoying",
			"answering",
			"apologising",
			"appearing",
			"applauding",
			"appreciating",
			"approving",
			"arguing",
			"arranging",
			"arresting",
			"arriving",
			"asking",
			"attaching",
			"attacking",
			"attempting",
			"attending",
			"attracting",
			"avoiding",
			"backing",
			"baking",
			"balancing",
			"banning",
			"banging",
			"baring",
			"batting",
			"bathing",
			"battling",
			"beaming",
			"begging",
			"behaving",
			"belonging",
			"bleaching",
			"blessing",
			"blinding",
			"blinking",
			"blotting",
			"blushing",
			"boasting",
			"boiling",
			"bolting",
			"bombing",
			"booking",
			"boring",
			"borrowing",
			"bouncing",
			"bowing",
			"boxing",
			"braking",
			"branching",
			"breathing",
			"bruising",
			"brushing",
			"bubbling",
			"bumping",
			"burning",
			"burying",
			"buzzing",
			"calculating",
			"calling",
			"camping",
			"caring",
			"carrying",
			"carving",
			"causing",
			"challenging",
			"changing",
			"charging",
			"chasing",
			"cheating",
			"checking",
			"cheering",
			"chewing",
			"choking",
			"chopping",
			"claiming",
			"clapping",
			"cleaning",
			"clearing",
			"clipping",
			"closing",
			"coaching",
			"coiling",
			"collecting",
			"colouring",
			"combing",
			"commanding",
			"communicating",
			"comparing",
			"competing",
			"complaining",
			"completing",
			"concentrating",
			"concerning",
			"confessing",
			"confusing",
			"connecting",
			"considering",
			"consisting",
			"containing",
			"continuing",
			"copying",
			"correcting",
			"coughing",
			"counting",
			"covering",
			"cracking",
			"crashing",
			"crawling",
			"crossing",
			"crushing",
			"crying",
			"curing",
			"curling",
			"curving",
			"cycling",
			"damaging",
			"dancing",
			"daring",
			"decaying",
			"deceiving",
			"deciding",
			"decorating",
			"delaying",
			"delighting",
			"delivering",
			"depending",
			"describing",
			"deserting",
			"deserving",
			"destroying",
			"detecting",
			"developing",
			"disagreeing",
			"disappearing",
			"disapproving",
			"disarming",
			"discovering",
			"disliking",
			"dividing",
			"doubling",
			"doubting",
			"dragging",
			"draining",
			"dreaming",
			"dressing",
			"dripping",
			"dropping",
			"drowning",
			"drumming",
			"drying",
			"dusting",
			"earning",
			"educating",
			"embarrassing",
			"employing",
			"emptying",
			"encouraging",
			"ending",
			"enjoying",
			"entering",
			"entertaining",
			"escaping",
			"examining",
			"exciting",
			"excusing",
			"exercising",
			"existing",
			"expanding",
			"expecting",
			"explaining",
			"exploding",
			"extending",
			"facing",
			"fading",
			"failing",
			"fancying",
			"fastening",
			"faxing",
			"fearing",
			"fencing",
			"fetching",
			"filing",
			"filling",
			"filming",
			"firing",
			"fitting",
			"fixing",
			"flapping",
			"flashing",
			"floating",
			"flooding",
			"flowing",
			"flowering",
			"folding",
			"following",
			"fooling",
			"forcing",
			"forming",
			"founding",
			"framing",
			"frightening",
			"frying",
			"gathering",
			"gazing",
			"glowing",
			"glueing",
			"grabbing",
			"grating",
			"greasing",
			"greeting",
			"grinning",
			"gripping",
			"groaning",
			"guaranteeing",
			"guarding",
			"guessing",
			"guiding",
			"hammering",
			"handing",
			"handling",
			"hanging",
			"happening",
			"harassing",
			"harming",
			"hating",
			"haunting",
			"heading",
			"healing",
			"heaping",
			"heating",
			"helping",
			"hooking",
			"hopping",
			"hoping",
			"hovering",
			"hugging",
			"humming",
			"hunting",
			"hurrying",
			"identifying",
			"ignoring",
			"imagining",
			"impressing",
			"improving",
			"including",
			"increasing",
			"influencing",
			"informing",
			"injecting",
			"injuring",
			"instructing",
			"intending",
			"interesting",
			"interfering",
			"interrupting",
			"introducing",
			"inventing",
			"inviting",
			"irritating",
			"itching",
			"jailing",
			"jamming",
			"jogging",
			"joining",
			"joking",
			"judging",
			"juggling",
			"jumping",
			"kicking",
			"killing",
			"kissing",
			"kneeling",
			"knitting",
			"knocking",
			"knotting",
			"labelling",
			"landing",
			"lasting",
			"laughing",
			"launching",
			"learning",
			"levelling",
			"licensing",
			"licking",
			"lying",
			"lightening",
			"liking",
			"listing",
			"listening",
			"living",
			"loading",
			"locking",
			"longing",
			"looking",
			"loving",
			"manning",
			"managing",
			"marching",
			"marking",
			"marrying",
			"matching",
			"mating",
			"mattering",
			"measuring",
			"meddling",
			"melting",
			"memorising",
			"mending",
			"messing up",
			"milking",
			"mining",
			"missing",
			"mixing",
			"moaning",
			"mooring",
			"mourning",
			"moving",
			"muddling",
			"mugging",
			"multiplying",
			"murdering",
			"nailing",
			"naming",
			"needing",
			"nesting",
			"nodding",
			"noting",
			"noticing",
			"numbering",
			"obeying",
			"objecting",
			"observing",
			"obtaining",
			"occurring",
			"offending",
			"offering",
			"opening",
			"ordering",
			"overflowing",
			"owing",
			"owning",
			"packing",
			"paddling",
			"painting",
			"parking",
			"parting",
			"passing",
			"pasting",
			"patting",
			"pausing",
			"pecking",
			"pedalling",
			"peeling",
			"peeping",
			"performing",
			"permitting",
			"phoning",
			"picking",
			"pinching",
			"pining",
			"placing",
			"planning",
			"planting",
			"playing",
			"pleasing",
			"plugging",
			"pointing",
			"poking",
			"polishing",
			"popping",
			"possessing",
			"posting",
			"pouring",
			"practising",
			"praying",
			"preaching",
			"preceding",
			"preferring",
			"preparing",
			"presenting",
			"preserving",
			"pressing",
			"pretending",
			"preventing",
			"pricking",
			"printing",
			"producing",
			"programming",
			"promising",
			"protecting",
			"providing",
			"pulling",
			"pumping",
			"punching",
			"puncturing",
			"punishing",
			"pushing",
			"questioning",
			"queueing",
			"racing",
			"radiating",
			"raining",
			"raising",
			"reaching",
			"realising",
			"receiving",
			"recognising",
			"recording",
			"reducing",
			"reflecting",
			"refusing",
			"regretting",
			"reigning",
			"rejecting",
			"rejoicing",
			"relaxing",
			"releasing",
			"relying on",
			"remaining",
			"remembering",
			"reminding",
			"removing",
			"repairing",
			"repeating",
			"replacing",
			"replying",
			"reporting",
			"reproducing",
			"requesting",
			"rescuing",
			"retiring",
			"returning",
			"rhyming",
			"rinsing",
			"risking",
			"robbing",
			"rocking",
			"rolling",
			"rotting",
			"rubbing",
			"ruining",
			"ruling",
			"rushing",
			"sacking",
			"sailing",
			"satisfying",
			"saving",
			"sawing",
			"scaring",
			"scattering",
			"scolding",
			"scorching",
			"scraping",
			"scratching",
			"screaming",
			"screwing",
			"scribbling",
			"scrubbing",
			"sealing",
			"searching",
			"separating",
			"serving",
			"settling",
			"shading",
			"sharing",
			"shaving",
			"sheltering",
			"shivering",
			"shocking",
			"shopping",
			"shrugging",
			"sighing",
			"signing",
			"signalling",
			"sinning",
			"sipping",
			"skiing",
			"skipping",
			"slapping",
			"slipping",
			"slowing",
			"smashing",
			"smelling",
			"smiling",
			"smoking",
			"snatching",
			"sneezing",
			"sniffing",
			"snoring",
			"snowing",
			"soaking",
			"soothing",
			"sounding",
			"sparing",
			"sparking",
			"sparkling",
			"spelling",
			"spilling",
			"spoiling",
			"spotting",
			"spraying",
			"sprouting",
			"squashing",
			"squeaking",
			"squealing",
			"squeezing",
			"staining",
			"stamping",
			"staring",
			"starting",
			"staying",
			"steering",
			"stepping",
			"stirring",
			"stitching",
			"stopping",
			"storing",
			"strapping",
			"strengthening",
			"stretching",
			"stripping",
			"stroking",
			"stuffing",
			"subtracting",
			"succeeding",
			"sucking",
			"suffering",
			"suggesting",
			"suiting",
			"supplying",
			"supporting",
			"supposing",
			"surprising",
			"surrounding",
			"suspecting",
			"suspending",
			"switching",
			"talking",
			"taming",
			"tapping",
			"tasting",
			"teasing",
			"telephoning",
			"tempting",
			"terrifying",
			"testing",
			"thanking",
			"thawing",
			"ticking",
			"tickling",
			"tying",
			"timing",
			"tipping",
			"tiring",
			"touching",
			"touring",
			"towing",
			"tracing",
			"trading",
			"training",
			"transporting",
			"trapping",
			"travelling",
			"treating",
			"trembling",
			"tricking",
			"tripping",
			"trotting",
			"troubling",
			"trusting",
			"trying",
			"tugging",
			"tumbling",
			"turning",
			"twisting",
			"typing",
			"undressing",
			"unfastening",
			"uniting",
			"unlocking",
			"unpacking",
			"untidying",
			"using",
			"vanishing",
			"visiting",
			"wailing",
			"waiting",
			"walking",
			"wandering",
			"wanting",
			"warming",
			"warning",
			"washing",
			"wasting",
			"watching",
			"watering",
			"waving",
			"weighing",
			"welcoming",
			"whining",
			"whipping",
			"whirling",
			"whispering",
			"whistling",
			"winking",
			"wiping",
			"wishing",
			"wobbling",
			"wondering",
			"working",
			"worrying",
			"wrapping",
			"wrecking",
			"wrestling",
			"wriggling",
			"x-raying",
			"yawning",
			"yelling",
			"zipping",
			"zooming"
			
			
	)),
	
	VERB_ZCOND(new PhraseList(
			"accepts",
			"adds",
			"admires",
			"admits",
			"advises",
			"affords",
			"agrees",
			"alerts",
			"allows",
			"amuses",
			"analyses",
			"announces",
			"annoys",
			"answers",
			"apologises",
			"appears",
			"applauds",
			"appreciates",
			"approves",
			"argues",
			"arranges",
			"arrests",
			"arrives",
			"asks",
			"attaches",
			"attacks",
			"attempts",
			"attends",
			"attracts",
			"avoids",
			"backs",
			"bakes",
			"balances",
			"bans",
			"bangs",
			"bares",
			"bats",
			"bathes",
			"battles",
			"beams",
			"begs",
			"behaves",
			"belongs",
			"bleaches",
			"blesses",
			"blinds",
			"blinks",
			"blots",
			"blushes",
			"boasts",
			"boils",
			"bolts",
			"bombs",
			"books",
			"bores",
			"borrows",
			"bounces",
			"bows",
			"boxes",
			"brakes",
			"branches",
			"breathes",
			"bruises",
			"brushes",
			"bubbles",
			"bumps",
			"burns",
			"buries",
			"buzzes",
			"calculates",
			"calls",
			"camps",
			"cares",
			"carries",
			"carves",
			"causes",
			"challenges",
			"changes",
			"charges",
			"chases",
			"cheats",
			"checks",
			"cheers",
			"chews",
			"chokes",
			"chops",
			"claims",
			"claps",
			"cleans",
			"clears",
			"clips",
			"closes",
			"coaches",
			"coils",
			"collects",
			"colours",
			"combs",
			"commands",
			"communicates",
			"compares",
			"competes",
			"complains",
			"completes",
			"concentrates",
			"concerns",
			"confesses",
			"confuses",
			"connects",
			"considers",
			"consists",
			"contains",
			"continues",
			"copies",
			"corrects",
			"coughs",
			"counts",
			"covers",
			"cracks",
			"crashes",
			"crawls",
			"crosses",
			"crushes",
			"cries",
			"cures",
			"curls",
			"curves",
			"cycles",
			"damages",
			"dances",
			"dares",
			"decays",
			"deceives",
			"decides",
			"decorates",
			"delays",
			"delights",
			"delivers",
			"depends",
			"describes",
			"deserts",
			"deserves",
			"destroys",
			"detects",
			"develops",
			"disagrees",
			"disappears",
			"disapproves",
			"disarms",
			"discovers",
			"dislikes",
			"divides",
			"doubles",
			"doubts",
			"drags",
			"drains",
			"dreams",
			"dresses",
			"drips",
			"drops",
			"drowns",
			"drums",
			"dries",
			"dusts",
			"earns",
			"educates",
			"embarrasses",
			"employs",
			"empties",
			"encourages",
			"ends",
			"enjoys",
			"enters",
			"entertains",
			"escapes",
			"examines",
			"excites",
			"excuses",
			"exercises",
			"exists",
			"expands",
			"expects",
			"explains",
			"explodes",
			"extends",
			"faces",
			"fades",
			"fails",
			"fancies",
			"fastens",
			"faxes",
			"fears",
			"fences",
			"fetches",
			"files",
			"fills",
			"films",
			"fires",
			"fits",
			"fixes",
			"flaps",
			"flashes",
			"floats",
			"floods",
			"flows",
			"flowers",
			"folds",
			"follows",
			"fools",
			"forces",
			"forms",
			"founds",
			"frames",
			"frightens",
			"fries",
			"gathers",
			"gazes",
			"glows",
			"glues",
			"grabs",
			"grates",
			"greases",
			"greets",
			"grins",
			"grips",
			"groans",
			"guarantees",
			"guards",
			"guesses",
			"guides",
			"hammers",
			"hands",
			"handles",
			"hangs",
			"happens",
			"harasses",
			"harms",
			"hates",
			"haunts",
			"heads",
			"heals",
			"heaps",
			"heats",
			"helps",
			"hooks",
			"hops",
			"hopes",
			"hovers",
			"hugs",
			"hums",
			"hunts",
			"hurries",
			"identifies",
			"ignores",
			"imagines",
			"impresses",
			"improves",
			"includes",
			"increases",
			"influences",
			"informs",
			"injects",
			"injures",
			"instructs",
			"intends",
			"interests",
			"interferes",
			"interrupts",
			"introduces",
			"invents",
			"invites",
			"irritates",
			"itches",
			"jails",
			"jams",
			"jogs",
			"joins",
			"jokes",
			"judges",
			"juggles",
			"jumps",
			"kicks",
			"kills",
			"kisses",
			"kneels",
			"knits",
			"knocks",
			"knots",
			"labels",
			"lands",
			"lasts",
			"laughs",
			"launches",
			"learns",
			"levels",
			"licenses",
			"licks",
			"lies",
			"lightens",
			"likes",
			"lists",
			"listens",
			"lives",
			"loads",
			"locks",
			"longs",
			"looks",
			"loves",
			"mans",
			"manages",
			"marches",
			"marks",
			"marries",
			"matches",
			"mates",
			"matters",
			"measures",
			"meddles",
			"melts",
			"memorises",
			"mends",
			"messes up",
			"milks",
			"mines",
			"misses",
			"mixes",
			"moans",
			"moors",
			"mourns",
			"moves",
			"muddles",
			"mugs",
			"multiplies",
			"murders",
			"nails",
			"names",
			"needs",
			"nests",
			"nods",
			"notes",
			"notices",
			"numbers",
			"obeys",
			"objects",
			"observes",
			"obtains",
			"occurs",
			"offends",
			"offers",
			"opens",
			"orders",
			"overflows",
			"owes",
			"owns",
			"packs",
			"paddles",
			"paints",
			"parks",
			"parts",
			"passes",
			"pastes",
			"pats",
			"pauses",
			"pecks",
			"pedals",
			"peels",
			"peeps",
			"performs",
			"permits",
			"phones",
			"picks",
			"pinches",
			"pines",
			"places",
			"plans",
			"plants",
			"plays",
			"pleases",
			"plugs",
			"points",
			"pokes",
			"polishes",
			"pops",
			"possesses",
			"posts",
			"pours",
			"practices",
			"prays",
			"preaches",
			"precedes",
			"prefers",
			"prepares",
			"presents",
			"preserves",
			"presses",
			"pretends",
			"prevents",
			"pricks",
			"prints",
			"produces",
			"programs",
			"promises",
			"protects",
			"provides",
			"pulls",
			"pumps",
			"punches",
			"punctures",
			"punishes",
			"pushes",
			"questions",
			"queues",
			"races",
			"radiates",
			"rains",
			"raises",
			"reaches",
			"realises",
			"receives",
			"recognises",
			"records",
			"reduces",
			"reflects",
			"refuses",
			"regrets",
			"reigns",
			"rejects",
			"rejoices",
			"relaxes",
			"releases",
			"relies",
			"remains",
			"remembers",
			"reminds",
			"removes",
			"repairs",
			"repeats",
			"replaces",
			"replies",
			"reports",
			"reproduces",
			"requests",
			"rescues",
			"retires",
			"returns",
			"rhymes",
			"rinses",
			"risks",
			"robs",
			"rocks",
			"rolls",
			"rots",
			"rubs",
			"ruins",
			"rules",
			"rushes",
			"sacks",
			"sails",
			"satisfies",
			"saves",
			"saws",
			"scares",
			"scatters",
			"scolds",
			"scorches",
			"scrapes",
			"scratches",
			"screams",
			"screws",
			"scribbles",
			"scrubs",
			"seals",
			"searches",
			"separates",
			"serves",
			"settles",
			"shades",
			"shares",
			"shaves",
			"shelters",
			"shivers",
			"shocks",
			"shops",
			"shrugs",
			"sighs",
			"signs",
			"signals",
			"sins",
			"sips",
			"skis",
			"skips",
			"slaps",
			"slips",
			"slows",
			"smashes",
			"smells",
			"smiles",
			"smokes",
			"snatches",
			"sneezes",
			"sniffs",
			"snores",
			"snows",
			"soaks",
			"soothes",
			"sounds",
			"spares",
			"sparks",
			"sparkles",
			"spells",
			"spills",
			"spoils",
			"spots",
			"sprays",
			"sprouts",
			"squashes",
			"squeaks",
			"squeals",
			"squeezes",
			"stains",
			"stamps",
			"stares",
			"starts",
			"stays",
			"steers",
			"steps",
			"stirs",
			"stitches",
			"stops",
			"stores",
			"straps",
			"strengthens",
			"stretches",
			"strips",
			"strokes",
			"stuffs",
			"subtracts",
			"succeeds",
			"sucks",
			"suffers",
			"suggests",
			"suits",
			"supplies",
			"supports",
			"supposes",
			"surprises",
			"surrounds",
			"suspects",
			"suspends",
			"switches",
			"talks",
			"tames",
			"taps",
			"tastes",
			"teases",
			"telephones",
			"tempts",
			"terrifies",
			"tests",
			"thanks",
			"thaws",
			"ticks",
			"tickles",
			"ties",
			"times",
			"tips",
			"tires",
			"touches",
			"tours",
			"tows",
			"traces",
			"trades",
			"trains",
			"transports",
			"traps",
			"travels",
			"treats",
			"trembles",
			"tricks",
			"trips",
			"trots",
			"troubles",
			"trusts",
			"tries",
			"tugs",
			"tumbles",
			"turns",
			"twists",
			"types",
			"undresses",
			"unfastens",
			"unites",
			"unlocks",
			"unpacks",
			"untidies",
			"uses",
			"vanishes",
			"visits",
			"wails",
			"waits",
			"walks",
			"wanders",
			"wants",
			"warms",
			"warns",
			"washes",
			"wastes",
			"watches",
			"waters",
			"waves",
			"weighs",
			"welcomes",
			"whines",
			"whips",
			"whirls",
			"whispers",
			"whistles",
			"winks",
			"wipes",
			"wishes",
			"wobbles",
			"wonders",
			"works",
			"worries",
			"wraps",
			"wrecks",
			"wrestles",
			"wriggles",
			"x-rays",
			"yawns",
			"yells",
			"zips",
			"zooms"
			
	)),
	
	
	
	TITLE_MALE(new PhraseList(
			"Doctor",
			"Surgeon",
			w("Baron", 0.8),
			w("Duke", 0.8),
			w("Lord", 0.8),
			w("Marquis", 0.8),
			w("Earl", 0.8),
			w("Baronet", 0.8),
			w("King", 0.8),
			w("Pope", 0.5),
			"Imam",
			"Prophet",
			"Sir",
			"Paladin",
			"Reverend",
			"Professor",
			"Admiral",
			"Captain",
			"Lieutenant",
			"Sergeant",
			"Corporal",
			"Private",
			"Midshipman",
			"Crewman",
			"Fleet-Admiral",
			"Rear-Admiral",
			"Airman",
			"Officer",
			"Emperor",
			"Guru",
			"Viceroy",
			"Grand Duke",
			"Archduke",
			"Prince",
			"Count",
			"Attorney General",
			"Chief Justice",
			"President",
			"Senator",
			"Privy Counsellor",
			"Justice",
			"Tribune",
			"Abbot",
			"Brother",
			"Friar",
			"Canon",
			"Saint",
			"Lord High Almoner",
			"Monsignor",
			"Colonel",
			"Brigadier",
			"Major",
			"Agent",
			"Principal",
			"Comrade",
			"First Citizen",
			"Great Leader",
			"Monsieur",
			"Rabbi",
			"Chief",
			"Legate",
			"Tetrarch",
			"Archon",
			"Consul",
			"Doge",
			"Lord Protector",
			"Imperator",
			"Triumvir",
			"Pharaoh",
			"Negus",
			"Tsar",
			"Shah",
			"Malik",
			w("Darth", 0.5),
			w("Grand Moff", 0.5),
			"Curator",
			"Registrar",
			"Sheriff",
			"Pursuivant",
			"Witch Hunter",
			"Patriarch",
			"Superintendent",
			"Detective Inspector",
			"Warden",
			"Grand Master",
			w("Grand High Steward", 0.3),
			w("Master of the Confectionery", 0.3),
			"Uncle",
			"Grandfather",
			"Grandad",
			"Great-Uncle"
			
	)),
	
	TITLE_FEMALE(new PhraseList(
			"Baroness",
			"Duchess",
			"Lady",
			"Marquess",
			"Baroness",
			"Queen",
			"Prophet",
			"Madame",
			"Paladin",
			"Reverend",
			"Professor",
			"Admiral",
			"Captain",
			"Lieutenant",
			"Sergeant",
			"Corporal",
			"Private",
			"Midshipman",
			"Crewman",
			"Fleet-Admiral",
			"Rear-Admiral",
			"Airman",
			"Officer",
			"Empress",
			"Grand Duchess",
			"Archduchess",
			"Princess",
			"Countess",
			"Attorney General",
			"Lady Justice",
			"President",
			"Senator",
			"Privy Counsellor",
			"Tribune",
			"Abbess",
			"Sister",
			"Canoness",
			"Saint",
			"Colonel",
			"Brigadier",
			"Major",
			"Agent",
			"Principal",
			"Comrade",
			"First Citizen",
			"Great Leader",
			"Mrs",
			"Tetrarch",
			"Archon",
			"Consulless",
			"Doge",
			"Lady Protector",
			"Imperatrix",
			"Triumvir",
			"Pharaoh",
			"Tsarina",
			w("Darth", 0.5),
			w("Grand Moff", 0.5),
			"Curator",
			"Registrar",
			"Sheriff",
			"Pursuivant",
			"Witch Hunter",
			"Matriarch",
			"Superintendent",
			"Detective Inspector",
			"Warden",
			w("Provincial Grand Mistress", 0.3),
			w("Provincial Grand High Steward", 0.3),
			w("Mistress of the Cheeseboard", 0.3),
			"Mother Superior",
			"Ms",
			"Miss",
			"Burgess",
			"Ambassador",
			"Viscountess",
			"Auntie",
			"Aunt",
			"Grandma",
			"Great-Grandma"
			
	)),
	
	LAST_TITLE(new PhraseList(
			"the Unpleasant",
			"the Pleasant",
			"the Hard",
			"the Chin",
			"the Legs",
			"- Eye of the Tiger",
			"- Storm of Excrement",
			"- Slayer of Men",
			"- Slayer of Women",
			"- Slayer of the Undead",
			"- Lord of the Underworld",
			"- Supreme High Bard",
			"- Man Mountain",
			"- Mountain King",
			"- Seller of Things",
			"- Slayer of Things",
			"- Owner of Cows",
			"the Banal",
			"the Largely Irrelevant",
			"the Underestimated",
			"the Porcine",
			"the Bovine",
			"the Melon",
			"- Finder of Graves",
			"- Seller of Corpses",
			"- Payer of Bills",
			"- Lender of Cash",
			"the Pustulent",
			"the Penguin",
			"- Player of Games",
			"- Player of Cards",
			"- Player of Monopoly"
	)),
	
	
	ADJ(new PhraseList(
			"good",
			"new",
			"first",
			"last",
			"long",
			"great",
			"little",
			"public",
			"large",
			"small",
			"different",
			"bad",
			"adorable",
			"beautiful",
			"clean",
			"sparkling",
			"ugly",
			"ugliest",
			"magnificent",
			"old-fashioned",
			"wide-eyed",
			"glamorous",
			"drab",
			"fancy",
			"red",
			"orange",
			"black",
			"white",
			"yellow",
			"green",
			"blue",
			"alive",
			"careful",
			"dead",
			"famous",
			"helpful",
			"immoral",
			"moral",
			"uninterested",
			"powerful",
			"rich",
			"poor",
			"agreeable",
			"witty",
			"zealous",
			"inexpensive",
			"expensive",
			"clever",
			"stupid",
			"pleasant",
			"unpleasant",
			"clumsy",
			"curved",
			"deep",
			"fat",
			"wide",
			"broad",
			"chubby",
			"thin",
			"straight",
			"high",
			"narrow",
			"round",
			"angry",
			"bewildered",
			"itchy",
			"scary",
			"worried",
			"uptight",
			"thoughtless",
			"big",
			"colossal",
			"steep",
			"mammoth",
			"tiny",
			"petite",
			"gigantic",
			"deafening",
			"scrawny",
			"immense",
			"voiceless",
			"whispering",
			"noisy",
			"quiet",
			"screeching",
			"faint",
			"ancient",
			"brief",
			"greasy",
			"young",
			"early",
			"bumpy",
			"cold",
			"cool",
			"freezing",
			"crooked",
			"wet",
			"hot",
			"warm",
			"curly",
			"damaged",
			"dirty",
			"filthy",
			"salty",
			"delicious",
			"tasteless",
			"abundant",
			"rotten",
			"aberrant",
			"abject",
			"absorbed",
			"absurd",
			"abnormal",
			"nippy",
			"noiseless",
			"nonchalant",
			"nondescript",
			"nonstop",
			"normal",
			"nostalgic",
			"nosy",
			"noxious",
			"numberless",
			"numerous",
			"nutritious",
			"nutty",
			"hard",
			"hard-to-find",
			"harmonious",
			"harsh",
			"hateful",
			"heady",
			"healthy",
			"heartbreaking",
			"heavenly",
			"heavy",
			"hellish",
			"helpful",
			"helpless",
			"hesitant",
			"hideous",
			"high",
			"highfalutin",
			"high-pitched",
			"hilarious",
			"hissing",
			"historical",
			"holistic",
			"empty",
			"enchanted",
			"enchanting",
			"encouraging",
			"endurable",
			"energetic",
			"enormous",
			"entertaining",
			"enthusiastic",
			"envious",
			"equable",
			"equal",
			w("erect", 0.25),
			"erratic",
			"ethereal",
			"evanescent",
			"evasive",
			"even",
			"excellent",
			"excited",
			"exciting",
			"exclusive",
			"exotic",
			"expensive",
			"extra-large",
			"extra-small",
			"exuberant",
			"exultant",
			"quaint",
			"quarrelsome",
			"questionable",
			"quick",
			"quickest",
			"quiet",
			"quirky",
			"quixotic",
			"quizzical",
			"grey",
			"grieving",
			"groovy",
			"grotesque",
			"grouchy",
			"grubby",
			"gruesome",
			"grumpy",
			"guarded",
			"guiltless",
			"gullible",
			"gusty",
			"guttural",
			"bombastic",
			"remarkable",
			"reminiscent",
			"repulsive",
			"resolute",
			"resonant",
			"responsible",
			"rhetorical",
			"right",
			"righteous",
			"rightful",
			"rigid",
			"ripe",
			"ritzy",
			"roasted",
			"robust",
			"romantic",
			"roomy",
			"rough",
			"round",
			"royal",
			"ruddy",
			"rude",
			"rural",
			"rustic",
			"ruthless",
			"vacuous",
			"vagabond",
			"vague",
			"valuable",
			"various",
			"vast",
			"vengeful",
			"venomous",
			"verdant",
			"versed",
			"victorious",
			"vigorous",
			"violent",
			"violet",
			"vivacious",
			"voiceless",
			"volatile",
			"voracious",
			"vulgar",
			"marvellous",
			"material",
			"materialistic",
			"mature",
			"mean",
			"measly",
			"meaty",
			"medical",
			"meek",
			"mellow",
			"melodic",
			"melted",
			"merciful",
			"messy",
			"mighty",
			"military",
			"milky",
			"mindless",
			"miniature",
			"minor",
			"miscreant",
			"misty",
			"mixed",
			"moaning",
			"modern",
			"mouldy",
			"momentous",
			"motionless",
			"mountainous",
			"muddled",
			"mundane",
			"murky",
			"mushy",
			"mute",
			"mysterious",
			"tense",
			"tenuous",
			"terrible",
			"terrific",
			"tested",
			"testy",
			"thankful",
			"therapeutic",
			"thick",
			"thin",
			"thinkable",
			"thirsty",
			"thirsty",
			"thoughtful",
			"thoughtless",
			"threatening",
			"thundering",
			"tidy",
			"tight",
			"tightfisted",
			"tired",
			"tiresome",
			"toothsome",
			"torpid",
			"tough",
			"towering",
			"tranquil",
			"trashy",
			"tremendous",
			"tricky",
			"trite",
			"troubled",
			"truculent",
			"true",
			"truthful",
			"typical"

	)),
	
	ANIMAL_PLURAL(new PhraseList(
			

			"raptors",
			"alligators",
			"antelopes",
			"ants",
			"apes",
			"asses",
			"baboons",
			"badgers",
			"bats",
			"bears",
			"beavers",
			"bees",
			"birds",
			"boar",
			"buffaloes",
			"bullfinches",
			"bullocks",
			"butterflies",
			"buzzards",
			"camels",
			"caribou",
			"cats",
			"caterpillars",
			"chickens",
			"cormorants",
			"coyotes",
			"cranes",
			"crocodiles",
			"crows",
			"curlews",
			"deer",
			"dogs",
			"dolphins",
			"doves",
			"ducks",
			"eagles",
			"eels",
			"elephants",
			"elk",
			"emus",
			"ferrets",
			"finches",
			"fishes",
			"flamingoes",
			"flies",
			"foxes",
			"frogs",
			"geese",
			"giraffes",
			"gnats",
			"goats",
			"gorillas",
			"grouse",
			"guineafowl",
			"hares",
			"hawks",
			"hedgehogs",
			"herons",
			"hippopotamuses",
			"hogs",
			"hornets",
			"horses",
			"hounds",
			"hyenas",
			"ibex",
			"ibises",
			"iguanas",
			"insects",
			"jackdaws",
			"jellyfishes",
			"kangaroos",
			"kittens",
			"leopards",
			"lions",
			"locusts",
			"mackerel",
			"magpies",
			"mice",
			"minnows",
			"moles",
			"monkeys",
			"moose",
			"moorhens",
			"mules",
			"owls",
			"oysters",
			"parrots",
			"pelicans",
			"pheasants",
			"pigs",
			"pigeons",
			"quail",
			"raccoons",
			"ravens",
			"rooks",
			"rhinoceroses",
			"seals",
			"sea urchins",
			"sheep",
			"snails",
			"snakes",
			"sparrows",
			"spiders",
			"squirrels",
			"storks",
			"swallows",
			"swans",
			"tigers",
			"toads",
			"turkeys",
			"trout",
			"walruses",
			"weasels",
			"whales",
			"wolves",
			"wombats",
			"wrens",
			"zebras"
			
			
	)),
	
	ANIMAL_SING(new PhraseList(

			"alligator",
			"antelope",
			"ant",
			"ape",
			"ass",
			"baboon",
			"badger",
			"bat",
			"bear",
			"beaver",
			"bee",
			"bird",
			"boar",
			"buffalo",
			"bullfinch",
			"bullock",
			"butterfly",
			"buzzard",
			"camel",
			"caribou",
			"cat",
			"caterpillar",
			"chicken",
			"cormorant",
			"coyote",
			"crane",
			"crocodile",
			"crow",
			"curlew",
			"deer",
			"dog",
			"dolphin",
			"dove",
			"duck",
			"eagle",
			"eel",
			"elephant",
			"elk",
			"emu",
			"ferret",
			"finch",
			"fish",
			"flamingo",
			"fly",
			"fox",
			"frog",
			"goose",
			"giraffe",
			"gnat",
			"goat",
			"gorilla",
			"grouse",
			"guineafowl",
			"hare",
			"hawk",
			"hedgehog",
			"heron",
			"hippopotamus",
			"hog",
			"hornet",
			"horse",
			"hound",
			"hyena",
			"ibex",
			"ibis",
			"iguana",
			"insect",
			"jackdaw",
			"jellyfish",
			"kangaroo",
			"kitten",
			"leopard",
			"lion",
			"locust",
			"mackerel",
			"magpie",
			"mouse",
			"minnow",
			"mole",
			"monkey",
			"moose",
			"moorhen",
			"mule",
			"owl",
			"oyster",
			"parrot",
			"pelican",
			"pheasant",
			"pig",
			"pigeon",
			"quail",
			"raccoon",
			"raven",
			"rook",
			"rhinoceros",
			"seal",
			"sea urchin",
			"sheep",
			"snail",
			"snake",
			"sparrow",
			"spider",
			"squirrel",
			"stork",
			"swallow",
			"swan",
			"tiger",
			"toad",
			"turkey",
			"trout",
			"walrus",
			"weasel",
			"whale",
			"wolf",
			"wombat",
			"wren",
			"zebra",
			"raptor"
		
			
	)),
	
		ADV(new PhraseList(
			"absentmindedly",
			"accidentally",
			"acidly",
			"actually",
			"adventurously",
			"almost",
			"always",
			"angrily",
			"annually",
			"anxiously",
			"arrogantly",
			"awkwardly",
			"bashfully",
			"beautifully",
			"bitterly",
			"bleakly",
			"blindly",
			"blissfully",
			"boastfully",
			"boldly",
			"bravely",
			"briefly",
			"brightly",
			"briskly",
			"broadly",
			"busily",
			"calmly",
			"carefully",
			"carelessly",
			"cautiously",
			"certainly",
			"cheerfully",
			"clearly",
			"cleverly",
			"closely",
			"coaxingly",
			"colorfully",
			"commonly",
			"continually",
			"coolly",
			"correctly",
			"courageously",
			"crossly",
			"cruelly ",
			"curiously",
			"daily",
			"daintily",
			"dearly",
			"deceivingly",
			"delightfully",
			"deeply",
			"defiantly",
			"deliberately",
			"delightfully",
			"diligently",
			"dimly",
			"doubtfully",
			"dreamily",
			"easily",
			"elegantly",
			"energetically",
			"enormously",
			"enthusiastically",
			"equally",
			"especially",
			"evenly",
			"exactly",
			"excitedly",
			"extremely",
			"fairly",
			"faithfully",
			"famously",
			"fatally",
			"ferociously",
			"fervently",
			"fiercely",
			"fondly",
			"foolishly",
			"fortunately",
			"frankly",
			"frantically",
			"freely",
			"frenetically",
			"frightfully",
			"fully",
			"furiously",
			"generally",
			"generously",
			"gently",
			"gladly",
			"gleefully",
			"gracefully",
			"gratefully",
			"greatly",
			"greedily",
			"happily",
			"hastily",
			"healthily",
			"heavily",
			"helpfully",
			"helplessly",
			"highly",
			"honestly",
			"hopelessly",
			"hungrily",
			"immediately",
			"innocently",
			"inquisitively",
			"instantly",
			"intensely",
			"intently",
			"interestingly",
			"inwardly",
			"irritably",
			"jaggedly",
			"jealously",
			"joyfully",
			"joyously",
			"jovially",
			"jubilantly",
			"judgementally",
			"justly",
			"keenly",
			"kiddingly",
			"kindheartedly",
			"kindly",
			"kissingly",
			"knavishly",
			"knowingly",
			"knowledgeably",
			"lazily",
			"less",
			"lightly",
			"limply",
			"loftily",
			"longingly",
			"loosely",
			"lovingly",
			"loudly",
			"loyally",
			"madly",
			"majestically",
			"meaningfully",
			"mechanically",
			"merrily",
			"miserably",
			"mockingly",
			"mortally",
			"mysteriously",
			"naturally",
			"nearly",
			"neatly",
			"needily",
			"nervously",
			"nicely",
			"noisily",
			"obediently",
			"obnoxiously",
			"oddly",
			"offensively",
			"officially",
			"openly",
			"optimistically",
			"overconfidently",
			"owlishly",
			"painfully",
			"partially",
			"patiently",
			"perfectly",
			"physically",
			"playfully",
			"politely",
			"poorly",
			"positively",
			"potentially",
			"powerfully",
			"promptly",
			"properly",
			"punctually",
			"quaintly",
			"quarrelsomely",
			"queasily",
			"queerly",
			"questionably",
			"questioningly",
			"quickly",
			"quietly",
			"quirkily",
			"quizzically",
			"rapidly",
			"rarely",
			"readily",
			"really",
			"reassuringly",
			"recklessly",
			"regularly",
			"reluctantly",
			"repeatedly",
			"reproachfully",
			"restfully",
			"righteously",
			"rightfully",
			"rigidly",
			"roughly",
			"rudely",
			"sadly",
			"safely",
			"scarcely",
			"scarily",
			"searchingly",
			"sedately",
			"seemingly",
			"selfishly",
			"separately",
			"seriously",
			"shakily",
			"sharply",
			"sheepishly",
			"shrilly",
			"shyly",
			"silently",
			"sleepily",
			"slowly",
			"smoothly",
			"softly",
			"solemnly",
			"solidly",
			"speedily",
			"stealthily",
			"sternly",
			"strictly",
			"successfully",
			"suddenly",
			"surprisingly",
			"suspiciously",
			"sweetly",
			"swiftly",
			"sympathetically",
			"tenderly",
			"tensely",
			"terribly",
			"thankfully",
			"thoroughly",
			"thoughtfully",
			"tightly",
			"tremendously",
			"triumphantly",
			"truly",
			"truthfully",
			"ultimately",
			"unabashedly",
			"unaccountably",
			"unbearably",
			"unethically",
			"unexpectedly",
			"unfortunately",
			"unimpressively",
			"unnaturally",
			"unnecessarily",
			"utterly",
			"upliftingly",
			"upwardly",
			"urgently",
			"usefully",
			"uselessly",
			"usually",
			"utterly",
			"vacantly",
			"vaguely",
			"vainly",
			"valiantly",
			"vastly",
			"verbally",
			"viciously",
			"victoriously",
			"violently",
			"vivaciously",
			"voluntarily",
			"warmly",
			"weakly",
			"wearily",
			"well",
			"wetly",
			"wholly",
			"wildly",
			"wilfully",
			"wisely",
			"woefully",
			"wonderfully",
			"worriedly",
			"wrongly",
			"yawningly",
			"yearningly",
			"yesterday",
			"yieldingly",
			"youthfully",
			"zealously",
			"zestfully",
			"zestily"

	
	
	
	
	)),
	
	FOOD_BASIC(new PhraseList(
			"toast",
			"bread",
			"cake",
			"lemon",
			"apple",
			"banana",
			"orange",
			"melon",
			"chocolate",
			"beef",
			"pork",
			"chicken",
			"fish",
			"salmon",
			"trout",
			"leg",
			"coffee",
			"beer",
			"cheese",
			"milk",
			"eyeball",
			"tomato",
			"liver",
			"spleen",
			"brain",
			"potato",
			"illegal drugs",
			"radiation",
			"paracetamol",
			"toblerone",
			"biscuit",
			"ham",
			"pea",
			"mustard",
			"barbecue sauce",
			"broccoli",
			"leek",
			"cabbage",
			"carrot",
			"toothpaste",
			"crab",
			"lobster",
			"lemming",
			"bee brain",
			"life essence",
			"human soul",
			"dirt",
			"brick",
			"sinew",
			"sugar",
			"salt",
			"pepper",
			"chilli pepper",
			"avocado",
			"icing sugar",
			"skull",
			"spinach",
			"rice",
			"egg",
			"bean",
			"runner bean",
			"green bean",
			"onion",
			"garlic",
			"orange peel",
			"mushroom",
			"blood",
			"black pudding",
			"offal",
			"hamster",
			"strawberry",
			"kiwi",
			"cherry",
			"raspberry",
			"passionfruit",
			"durian fruit",
			"goat's cheese",
			"wasp",
			"infant",
			"peanut butter",
			"butter",
			"margerine",
			"coconut",
			"#THING#",
			""

			
			
	)),
	
	FOOD_PRIMARY(new PhraseList(
			"crisp",
			"baked",
			"boiled",
			"steamed",
			"braised",
			"burnt",
			"warming",
			"fried",
			"basted",
			"glazed",
			"frozen",
			"smoked",
			"sliced",
			"diced",
			"suspicious",
			"battered",
			"blanched",
			"broiled",
			"creamed",
			"cured",
			"garnished",
			"grated",
			"ground",
			"peeled",
			"pickled",
			"pitted",
			"reduced",
			"pureed",
			"scalloped",
			"sauted",
			"seared",
			"shredded",
			"skimmed",
			"steeped",
			"stirred",
			"whipped",
			"sterilised",
			"roast",
			"scalded",
			"vacuum-packed",
			"rendered",
			"poached",
			"pan-fried",
			"marinaded",
			"barbecued"

			
	)),
	
	FOOD_PRODUCT(new PhraseList(
			"cake",
			"buns",
			"soup",
			"pasta",
			"stew",
			"broth",
			"sandwiches",
			"platter",
			"rolls",
			"pudding",
			"pizza",
			"doughballs",
			"doughnuts",
			"meatballs",
			"paninis",
			"pie",
			"salad",
			"tagine",
			"loaves",
			"smoothie",
			"milkshake",
			"ale",
			"hotpot",
			"bake",
			"sausages",
			"sauce",
			"quiche",
			"flan",
			"casserole",
			"slop",
			"bucket",
			"lasagne",
			"dumplings",
			"spread",
			"confit",
			"parfait",
			"preserve",
			"fool",
			"soufflé",
			"jelly",
			"terrine",
			"paté",
			"goujons",
			"pancakes",
			"wraps",
			"muffins",
			"crumpets",
			"tapas",
			"risotto",
			"chutney",
			"omelette",
			"fritata",
			"mash",
			"curry",
			"cobbler",
			"pudd'n",
			"mess",
			"mousse",
			"crumble",
			"macaroons"
	
	
	)),
	
	
	
	RECIPE_BOOKTYPE(new PhraseList(
			"How to Cook",
			"Making",
			"Perfect",
			"Decorative",
			"An Artisan's Guide to",
			"Mrs Beeton's",
			"Producing",
			"Mass Producing",
			"Catering 101 :"
			
	)),
	
	
	PLACE_1(new PhraseList(
			"South",
			"North",
			"East",
			"West",
			"Cave",
			"Spike",
			"Pork",
			"Beef",
			"Aver",
			"Toad",
			"Left",
			"Right",
			"Best",
			"Leaf",
			"Tumble",
			"Sugar",
			"Toast",
			"Glory",
			"Blood",
			"Fish",
			"Cold",
			"Old",
			"Tun",
			"Bum",
			"Ast",
			"New",
			"Blue"
			
			
	)),
	
	PLACE_2(new PhraseList(
			"well",
			"hills",
			"borough",
			"ham",
			"bury",
			"leford",
			"ridge",
			"lebury",
			"town",
			"ville",
			"wells",
			"lico",
			"ford",
			"bridge",
			"-Eaton",
			"stein",
			"castle"
			
	)),
	
	THE(new PhraseList(
			"The"
	)),
	
	NEWS_TITLE_1(new PhraseList(
			"Daily",
			"Bi-Annual",
			"Global",
			"Local",
			"Irrelevant",
			"Important",
			"Highly Exciting",
			"Weekly",
			"Crafter's",
			"Miner's",
			"Builder's",
			"Glorious",
			"Annual",
			"Evening",
			"Nightly",
			"Morning",
			"Outrageous",
			"Irregular",
			"Regular",
			"Local",
			"Afternoon",
			"Mid-Morning",
			"Three o' Clock",
			"Ten Past Four",
			"Uplifting",
			"Enthusiast's"
			
	
			
	)),
	
	NEWS_TITLE_2(new PhraseList(
			"Star",
			"Gazette",
			"Moon",
			"Tribune",
			"Archon",
			"Paper",
			"Broadsheet",
			"Tabloid",
			"Update",
			"Pack of Lies",
			"Times",
			"Telegraph",
			"Journal",
			"News",
			"Post",
			"Chronicle",
			"Inquirer",
			"Constitution",
			"Republic",
			"Advertiser",
			"Standard",
			"Patriot",
			"Courier",
			"Sentinel",
			"Eagle",
			"Republican",
			"Independent",
			"Observer",
			"Guardian",
			"Mail",
			"Metro",
			"Herald",
			"Express",
			"Mercury",
			"Echo",
			"Recorder",
			"Champion",
			"Hermes",
			"Pluto",
			"Broadcast",
			"Telescope",
			"Interstellar Communique",
			"Almanac"
	
	
	
	)),
	
	PRONOUNS(new PhraseList(
			pn("I",		"me",	"my",		"mine",		"myself", 1.0),
			pn("you",	"you",	"your",		"yours",	"yourself", 1.0),
			pn("he",	"him",	"his",		"his",		"himself", 1.0),
			pn("she",	"her",	"her",		"hers",		"herself", 1.0),
			pn("it",	"it",	"its",		"its",		"itself", 1.0),
			pn("we",	"us",	"our",		"ours",		"ourselves", 1.0),
			pn("you",	"you",	"your",		"yours",	"yourselves", 1.0),
			pn("they",	"them",	"their",	"theirs",	"themselves", 1.0)
	)),
	
	MC_ITEM(null){
		private boolean cached = false;
		private List<ItemStack> cache;
		private String[] banned = new String[] {
			"facade:",
			"slab",
			"panel",
			"cover",
			"post",
			"corner",
			"nook",
			"spawn",
			"(",
			")",
			"[",
			"]",
			"<",
			">",
		};
		
		@Override
		public Phrase getPhrase() {
			if (!cached) { cache(); }
			if (this.cache.size() == 0) {
				return new Phrase("[NO ITEM]");
			}
			String item = cache.get(rand.nextInt(cache.size())).getDisplayName();
			return w(item,1.0);
		}
		
		@SuppressWarnings("unchecked")
		private void cache() {
			this.cache = new ArrayList<ItemStack>();
			
			Iterator<Item> iter = Item.itemRegistry.iterator();
			
			List<ItemStack> items = new ArrayList<ItemStack>();
			while(iter.hasNext()) {
				Item item = iter.next();
				
				if (!(item instanceof ItemBlock)){
					item.getSubItems(item, null, items);
				}
			}
			
			items:
			for (ItemStack stack : items) {
				String name = stack.getDisplayName().toLowerCase();
				for (String ban : banned) {
					if (name.contains(ban)) {
						continue items;
					}
				}
				this.cache.add(stack);
			}
		}
	},
	
	
	MC_BLOCK(null){
		private boolean cached = false;
		private List<ItemStack> cache;
		private String[] banned = new String[] {
			"facade:",
			"slab",
			"panel",
			"cover",
			"post",
			"corner",
			"nook",
			"spawn",
			"(",
			")",
			"[",
			"]",
			"<",
			">",
		};
		
		@Override
		public Phrase getPhrase() {
			if (!cached) { cache(); }
			if (this.cache.size() == 0) {
				return new Phrase("[NO BLOCK]");
			}
			String item = cache.get(rand.nextInt(cache.size())).getDisplayName();
			return w(item,1.0);
		}
		
		@SuppressWarnings("unchecked")
		private void cache() {
			this.cache = new ArrayList<ItemStack>();
			
			Iterator<Item> iter = Item.itemRegistry.iterator();
			
			List<ItemStack> items = new ArrayList<ItemStack>();
			while(iter.hasNext()) {
				Item item = iter.next();
				
				if ((item instanceof ItemBlock)){
					item.getSubItems(item, null, items);
				}
			}
			
			items:
			for (ItemStack stack : items) {
				String name = stack.getDisplayName().toLowerCase();
				for (String ban : banned) {
					if (name.contains(ban)) {
						continue items;
					}
				}
				this.cache.add(stack);
			}
		}
	},
	
	;
	
	public static final String delimiter = "#";
	public static final String seperator = "\\+";
	
	public final PhraseList words;
	private static Random rand = new Random();
	
	private Symbol(PhraseList words) {
		this.words = words;
	}
	
	public String get(){
		return this.getPhrase().text;
	}
	
	public Phrase getPhrase() {
		Phrase p = this.words.get(rand);
		return p.copy();
	}
}

